// GENERATED by scripts/migration/gen-content.mjs — 2026-08-17
// Source: snowpro-c03-guide RECALL+RECALL_EXTRA (52 recall) + 17 trap callouts (mechanical front/back split)
// Do not hand-edit content items: regenerate, or record any manual edit in MIGRATION_NOTES.md.
import type { Card } from "../../schema";

export const cards: Card[] = [
  {
    "id": "snowpro-c03-recall-d1-001",
    "examId": "snowpro-c03",
    "domainId": "d1",
    "type": "recall",
    "front": "Name the three layers of Snowflake architecture and one responsibility of each.",
    "back": "Storage — immutable micro-partitions on cloud object storage. Compute — virtual warehouses execute queries. Cloud Services — auth, metadata, parsing, optimization, access control.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-recall-d1-002",
    "examId": "snowpro-c03",
    "domainId": "d1",
    "type": "recall",
    "front": "List the four editions in order, and the marquee features that arrive at each step.",
    "back": "Standard (1-day Time Travel) → Enterprise (90-day TT, Materialized Views, MCW, Search Optimization) → Business Critical (Tri-Secret Secure, PrivateLink, HIPAA/PCI) → VPS (dedicated isolation).",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-recall-d1-003",
    "examId": "snowpro-c03",
    "domainId": "d1",
    "type": "recall",
    "front": "From memory: all seven table types.",
    "back": "Permanent, Transient, Temporary, External, Iceberg, Dynamic, Hybrid (Unistore).",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-recall-d1-004",
    "examId": "snowpro-c03",
    "domainId": "d1",
    "type": "recall",
    "front": "WHY does a transient table cost less to store than a permanent one?",
    "back": "It keeps no 7-day Fail-safe copy and at most 1 day of Time Travel, so far less historical data is retained behind the scenes.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-recall-d1-005",
    "examId": "snowpro-c03",
    "domainId": "d1",
    "type": "recall",
    "front": "Name the four Cortex services and the input each takes.",
    "back": "AI SQL functions (a string column), Cortex Search (unstructured documents), Cortex Analyst (an NL question plus a semantic model), Document AI (PDFs and images).",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-recall-d1-006",
    "examId": "snowpro-c03",
    "domainId": "d1",
    "type": "recall",
    "front": "Credits per hour for XS, S, M, L, XL?",
    "back": "1, 2, 4, 8, 16 — doubling per size, billed per second with a 60-second minimum.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-recall-d2-001",
    "examId": "snowpro-c03",
    "domainId": "d2",
    "type": "recall",
    "front": "Recite the six system-defined roles and one duty for each.",
    "back": "ORGADMIN (org-level ops), ACCOUNTADMIN (full account authority), SECURITYADMIN (grants globally), USERADMIN (creates users/roles), SYSADMIN (creates DBs/warehouses; parent for custom roles), PUBLIC (default for everyone).",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-recall-d2-002",
    "examId": "snowpro-c03",
    "domainId": "d2",
    "type": "recall",
    "front": "WHY should custom roles roll up under SYSADMIN instead of being used from ACCOUNTADMIN?",
    "back": "Custom roles are not auto-inherited; granting them to SYSADMIN gives object admins visibility and control while keeping ACCOUNTADMIN for rare, high-privilege actions.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-recall-d2-003",
    "examId": "snowpro-c03",
    "domainId": "d2",
    "type": "recall",
    "front": "Name four authentication methods Snowflake supports beyond passwords.",
    "back": "MFA, SSO (SAML 2.0), OAuth (provider or client), key-pair authentication.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-recall-d2-004",
    "examId": "snowpro-c03",
    "domainId": "d2",
    "type": "recall",
    "front": "State the difference between a masking policy and a row access policy.",
    "back": "Masking policies transform column values per query context; row access policies filter which rows a role can see at all.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-recall-d2-005",
    "examId": "snowpro-c03",
    "domainId": "d2",
    "type": "recall",
    "front": "A resource monitor hits a threshold. Name its three possible actions.",
    "back": "Notify; suspend (let running queries finish); suspend immediate (cancel running queries).",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-recall-d2-006",
    "examId": "snowpro-c03",
    "domainId": "d2",
    "type": "recall",
    "front": "What does Trust Center evaluate?",
    "back": "Security posture: MFA coverage, network policy usage, and risky account configurations.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-recall-d3-001",
    "examId": "snowpro-c03",
    "domainId": "d3",
    "type": "recall",
    "front": "Write the stage symbols for user, table, and named stages.",
    "back": "@~ (user), @%tablename (table), @stage_name (named internal or external).",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-recall-d3-002",
    "examId": "snowpro-c03",
    "domainId": "d3",
    "type": "recall",
    "front": "Name the four ON_ERROR modes for COPY INTO.",
    "back": "CONTINUE, SKIP_FILE, SKIP_FILE_n%, ABORT_STATEMENT.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-recall-d3-003",
    "examId": "snowpro-c03",
    "domainId": "d3",
    "type": "recall",
    "front": "WHY would you choose Snowpipe Streaming over classic Snowpipe?",
    "back": "You need row-level ingestion with seconds-level latency (CDC, clickstream, IoT) via the Ingest SDK — no files landing in a stage, different pricing model.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-recall-d3-004",
    "examId": "snowpro-c03",
    "domainId": "d3",
    "type": "recall",
    "front": "Recite the decision rule: Dynamic Table vs Streams + Tasks.",
    "back": "Declarative target state with automatic refresh on a lag → Dynamic Table. Change-data-capture semantics with custom MERGE logic → Streams + Tasks.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-recall-d3-005",
    "examId": "snowpro-c03",
    "domainId": "d3",
    "type": "recall",
    "front": "What does a storage integration eliminate the need for?",
    "back": "Embedding cloud credentials in stage definitions — access is delegated through cloud IAM trust instead.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-recall-d3-006",
    "examId": "snowpro-c03",
    "domainId": "d3",
    "type": "recall",
    "front": "List six supported load file formats.",
    "back": "CSV, JSON, Parquet, Avro, ORC, XML.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-recall-d4-001",
    "examId": "snowpro-c03",
    "domainId": "d4",
    "type": "recall",
    "front": "Name the three caches, where each lives, and when each is lost or invalidated.",
    "back": "Result cache — Cloud Services, 24h extended to 31 days on reuse, invalidated by underlying data change. Metadata cache — Cloud Services, persistent. Warehouse data cache — local SSD, lost on suspend.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-recall-d4-002",
    "examId": "snowpro-c03",
    "domainId": "d4",
    "type": "recall",
    "front": "A Query Profile shows bytes spilled to remote storage. What do you do, and why?",
    "back": "Scale the warehouse UP — spilling means the query exceeded memory, and remote spill is the most expensive symptom of an undersized warehouse.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-recall-d4-003",
    "examId": "snowpro-c03",
    "domainId": "d4",
    "type": "recall",
    "front": "Give the scenario for scale up vs the scenario for scale out.",
    "back": "Scale up: one heavy query, big joins, spilling. Scale out (Multi-Cluster, Enterprise+): many concurrent users and queuing.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-recall-d4-004",
    "examId": "snowpro-c03",
    "domainId": "d4",
    "type": "recall",
    "front": "WHY can aggressive auto-suspend make repeated queries slower?",
    "back": "Suspending drops the warehouse data cache, so the next queries read micro-partitions cold from remote storage.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-recall-d4-005",
    "examId": "snowpro-c03",
    "domainId": "d4",
    "type": "recall",
    "front": "When should you NOT add a clustering key?",
    "back": "On small tables — Automatic Clustering burns credits with little pruning benefit; reserve it for roughly 1 TB+ tables with selective filters.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-recall-d4-006",
    "examId": "snowpro-c03",
    "domainId": "d4",
    "type": "recall",
    "front": "Say aloud the FLATTEN pattern for exploding a nested array.",
    "back": "SELECT f.value:field::STRING FROM tbl t, LATERAL FLATTEN(input => t.payload:items) f;",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-recall-d5-001",
    "examId": "snowpro-c03",
    "domainId": "d5",
    "type": "recall",
    "front": "Time Travel vs Fail-safe: durations, who accesses each, and which table types lack Fail-safe.",
    "back": "Time Travel: 1 day default, up to 90 on Enterprise+ for permanent tables, user-accessible (AT, BEFORE, UNDROP). Fail-safe: 7 more days, Snowflake support only. Transient and temporary tables have none.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-recall-d5-002",
    "examId": "snowpro-c03",
    "domainId": "d5",
    "type": "recall",
    "front": "WHY is a zero-copy clone instant and free at creation?",
    "back": "It is a metadata operation pointing at the same immutable micro-partitions; storage accrues only as clone and source diverge.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-recall-d5-003",
    "examId": "snowpro-c03",
    "domainId": "d5",
    "type": "recall",
    "front": "A provider must share to a consumer in a different region. Recall both valid paths.",
    "back": "Replicate the database to the consumer region and share there, or publish a Marketplace listing (public or private).",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-recall-d5-004",
    "examId": "snowpro-c03",
    "domainId": "d5",
    "type": "recall",
    "front": "What is a reader account, and who pays for its compute?",
    "back": "A provider-managed account for consumers without their own Snowflake contract; the provider provisions and pays.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-recall-d1-007",
    "examId": "snowpro-c03",
    "domainId": "d1",
    "type": "recall",
    "front": "Recite the two multi-cluster modes and the two scaling policies.",
    "back": "Modes: Maximized (all clusters always on) and Auto-scale (between min and max). Policies: Standard (start clusters eagerly to avoid queuing) and Economy (conserve credits, tolerate queuing).",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-recall-d1-008",
    "examId": "snowpro-c03",
    "domainId": "d1",
    "type": "recall",
    "front": "WHY does Cloud Services usually cost nothing extra?",
    "back": "It is only billed when its daily consumption exceeds 10% of the day’s warehouse credit usage — most workloads stay under that.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-recall-d1-009",
    "examId": "snowpro-c03",
    "domainId": "d1",
    "type": "recall",
    "front": "Recall the encryption story end to end.",
    "back": "AES-256 always on, hierarchical key model, automatic 30-day key rotation, optional annual rekeying, and Tri-Secret Secure (customer key + Snowflake key) on Business Critical.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-recall-d1-010",
    "examId": "snowpro-c03",
    "domainId": "d1",
    "type": "recall",
    "front": "What are the restrictions on materialized views?",
    "back": "Single table only — no joins — plus limits on certain functions; maintenance is automatic, serverless, and billed.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-recall-d1-011",
    "examId": "snowpro-c03",
    "domainId": "d1",
    "type": "recall",
    "front": "List the serverless features that bill without your warehouse.",
    "back": "Snowpipe, Snowpipe Streaming, serverless tasks, Automatic Clustering, materialized view maintenance, Search Optimization, Query Acceleration.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-recall-d2-007",
    "examId": "snowpro-c03",
    "domainId": "d2",
    "type": "recall",
    "front": "ACCOUNT_USAGE vs INFORMATION_SCHEMA — recall both tradeoffs.",
    "back": "ACCOUNT_USAGE: latency from minutes up to a few hours, ~365 days of history, account-wide. INFORMATION_SCHEMA: near real-time, shorter retention, per-database.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-recall-d2-008",
    "examId": "snowpro-c03",
    "domainId": "d2",
    "type": "recall",
    "front": "Recite the default role hierarchy from ACCOUNTADMIN down.",
    "back": "ACCOUNTADMIN → SECURITYADMIN (→ USERADMIN) and ACCOUNTADMIN → SYSADMIN; custom roles roll up under SYSADMIN; PUBLIC sits at the bottom for everyone.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-recall-d2-009",
    "examId": "snowpro-c03",
    "domainId": "d2",
    "type": "recall",
    "front": "What is a future grant and why does it matter?",
    "back": "GRANT … ON FUTURE objects in a schema/database auto-applies privileges to objects created later, so new tables are usable without re-granting.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-recall-d2-010",
    "examId": "snowpro-c03",
    "domainId": "d2",
    "type": "recall",
    "front": "Network policy precedence — say the rule.",
    "back": "A user-level network policy overrides the account-level policy for that user.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-recall-d2-011",
    "examId": "snowpro-c03",
    "domainId": "d2",
    "type": "recall",
    "front": "Name three programmatic authentication paths for a service account.",
    "back": "Key-pair authentication, OAuth, and (where unavoidable) password + MFA exemptions via service user types — key-pair is the standard answer.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-recall-d3-007",
    "examId": "snowpro-c03",
    "domainId": "d3",
    "type": "recall",
    "front": "PUT vs GET — recall both directions and where they run.",
    "back": "PUT uploads local files to an internal stage; GET downloads staged files locally. Both run from SnowSQL / Snowflake CLI / drivers, not the Snowsight worksheet.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-recall-d3-008",
    "examId": "snowpro-c03",
    "domainId": "d3",
    "type": "recall",
    "front": "How long is bulk COPY load metadata kept, and what does it prevent?",
    "back": "64 days; it prevents re-loading the same files (duplicate protection).",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-recall-d3-009",
    "examId": "snowpro-c03",
    "domainId": "d3",
    "type": "recall",
    "front": "Recite the recommended load file sizing guidance.",
    "back": "Aim for roughly 100–250 MB compressed per file; split larger, combine smaller, to maximize parallel load across warehouse threads.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-recall-d3-010",
    "examId": "snowpro-c03",
    "domainId": "d3",
    "type": "recall",
    "front": "Name the three stream types and where each applies.",
    "back": "Standard (full insert/update/delete CDC on tables), append-only (tables, inserts only), insert-only (external tables).",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-recall-d3-011",
    "examId": "snowpro-c03",
    "domainId": "d3",
    "type": "recall",
    "front": "WHY does SELECTing a stream not consume it?",
    "back": "Offsets advance only when stream rows are used in DML inside a transaction — reads are side-effect free so multiple consumers can inspect first.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-recall-d4-007",
    "examId": "snowpro-c03",
    "domainId": "d4",
    "type": "recall",
    "front": "Recall the three conditions for a result cache hit.",
    "back": "Byte-identical query text, unchanged underlying data, and the executing role holds the necessary privileges (with result reuse enabled).",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-recall-d4-008",
    "examId": "snowpro-c03",
    "domainId": "d4",
    "type": "recall",
    "front": "LIKE vs CLONE — one breath.",
    "back": "LIKE = same structure, empty table. CLONE = zero-copy of structure AND data at that instant.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-recall-d4-009",
    "examId": "snowpro-c03",
    "domainId": "d4",
    "type": "recall",
    "front": "What is the VARIANT size limit and one load option that helps avoid hitting it?",
    "back": "16 MB per value; STRIP_OUTER_ARRAY = TRUE loads array elements as separate rows instead of one giant value.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-recall-d4-010",
    "examId": "snowpro-c03",
    "domainId": "d4",
    "type": "recall",
    "front": "UDF vs UDTF vs stored procedure — recall all three.",
    "back": "UDF returns a scalar used in expressions; UDTF returns rows and is queried in FROM; a stored procedure performs actions and is invoked with CALL.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-recall-d4-011",
    "examId": "snowpro-c03",
    "domainId": "d4",
    "type": "recall",
    "front": "Explain pruning to a colleague in two sentences.",
    "back": "Every micro-partition stores min/max metadata per column. Filters let Snowflake skip partitions whose ranges cannot match, so well-ordered data means most of the table is never read.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-recall-d5-005",
    "examId": "snowpro-c03",
    "domainId": "d5",
    "type": "recall",
    "front": "Recall what a clone does NOT bring along.",
    "back": "External tables and internal named stages are excluded; grants on child objects are not copied unless COPY GRANTS is used.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-recall-d5-006",
    "examId": "snowpro-c03",
    "domainId": "d5",
    "type": "recall",
    "front": "List everything a share consumer cannot do.",
    "back": "No DML on shared objects, no Time Travel against shared data, no cloning shared objects, and no re-sharing to other accounts.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-recall-d5-007",
    "examId": "snowpro-c03",
    "domainId": "d5",
    "type": "recall",
    "front": "Recite the three AT | BEFORE reference points with syntax hints.",
    "back": "AT(TIMESTAMP => …), AT(OFFSET => -3600), and BEFORE(STATEMENT => 'query-id').",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-recall-d5-008",
    "examId": "snowpro-c03",
    "domainId": "d5",
    "type": "recall",
    "front": "WHY do reader accounts exist, and who pays compute in them?",
    "back": "They serve consumers with no Snowflake contract; the provider provisions the account and pays for its compute.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-trap-001",
    "examId": "snowpro-c03",
    "domainId": "d1",
    "type": "trap",
    "front": "⚠️ Trap: \"Which feature requires Enterprise?\" questions are frequent.",
    "back": "\"Which feature requires Enterprise?\" questions are frequent. Memorize the Enterprise list above cold.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-trap-002",
    "examId": "snowpro-c03",
    "domainId": "d1",
    "type": "trap",
    "front": "⚠️ Trap: Search vs Analyst.",
    "back": "Search vs Analyst. Unstructured document retrieval = Cortex Search. Natural-language questions over structured tables = Cortex Analyst. The exam swaps them deliberately.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-trap-003",
    "examId": "snowpro-c03",
    "domainId": "d2",
    "type": "trap",
    "front": "⚠️ Trap: ACCOUNTADMIN does NOT automatically see custom roles.",
    "back": "ACCOUNTADMIN does NOT automatically see custom roles. Best practice is a custom role hierarchy rolled up under SYSADMIN.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-trap-004",
    "examId": "snowpro-c03",
    "domainId": "d3",
    "type": "trap",
    "front": "⚠️ Trap: Different SDKs, different latency, different pricing.",
    "back": "Different SDKs, different latency, different pricing. If the scenario says files in a stage, it is Snowpipe. If it says rows arriving continuously with seconds-level freshness, it is Snowpipe Streaming.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-trap-005",
    "examId": "snowpro-c03",
    "domainId": "d4",
    "type": "trap",
    "front": "⚠️ Trap: auto-suspend saves credits but drops the warehouse data cache.",
    "back": "auto-suspend saves credits but drops the warehouse data cache. Aggressive suspend + repetitive queries = cold reads. The exam tests this tension.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-trap-006",
    "examId": "snowpro-c03",
    "domainId": "d5",
    "type": "trap",
    "front": "⚠️ Trap: Transient and temporary tables get short Time Travel but NO Fail-safe.",
    "back": "Transient and temporary tables get short Time Travel but NO Fail-safe. The exam loves this distinction — and it is why transient tables cost less to store.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-trap-007",
    "examId": "snowpro-c03",
    "domainId": "d5",
    "type": "trap",
    "front": "⚠️ Trap: if the scenario says cross-region, \"direct share\" is wrong.",
    "back": "if the scenario says cross-region, \"direct share\" is wrong. Replicate first, or use a listing.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-trap-008",
    "examId": "snowpro-c03",
    "domainId": "d1",
    "type": "trap",
    "front": "⚠️ Why candidates fail #1: Studying only from pre-C03 materials — missing Cortex, Iceberg, Dynamic Tables, Snowpipe Streaming entirely.",
    "back": "Studying only from pre-C03 materials — missing Cortex, Iceberg, Dynamic Tables, Snowpipe Streaming entirely.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-trap-009",
    "examId": "snowpro-c03",
    "domainId": null,
    "type": "trap",
    "front": "⚠️ Why candidates fail #2: No hands-on reps.",
    "back": "No hands-on reps. The questions are scenario-heavy; you cannot memorize your way to 750.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-trap-010",
    "examId": "snowpro-c03",
    "domainId": "d4",
    "type": "trap",
    "front": "⚠️ Why candidates fail #3: Can define micro-partitions but cannot read a Query Profile.",
    "back": "Can define micro-partitions but cannot read a Query Profile. Spend real hours in profiles.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-trap-011",
    "examId": "snowpro-c03",
    "domainId": "d2",
    "type": "trap",
    "front": "⚠️ Why candidates fail #4: RBAC inheritance confusion — ACCOUNTADMIN does not inherit custom roles unless granted.",
    "back": "RBAC inheritance confusion — ACCOUNTADMIN does not inherit custom roles unless granted.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-trap-012",
    "examId": "snowpro-c03",
    "domainId": "d5",
    "type": "trap",
    "front": "⚠️ Why candidates fail #5: Time Travel vs Fail-safe: user-accessible vs support-only; transient tables have no Fail-safe.",
    "back": "Time Travel vs Fail-safe: user-accessible vs support-only; transient tables have no Fail-safe.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-trap-013",
    "examId": "snowpro-c03",
    "domainId": "d3",
    "type": "trap",
    "front": "⚠️ Why candidates fail #6: Snowpipe vs Snowpipe Streaming: micro-batch minutes vs row-level seconds.",
    "back": "Snowpipe vs Snowpipe Streaming: micro-batch minutes vs row-level seconds.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-trap-014",
    "examId": "snowpro-c03",
    "domainId": "d1",
    "type": "trap",
    "front": "⚠️ Why candidates fail #7: Edition blindness.",
    "back": "Edition blindness. Memorize which features need Enterprise.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-trap-015",
    "examId": "snowpro-c03",
    "domainId": null,
    "type": "trap",
    "front": "⚠️ Why candidates fail #8: Pacing.",
    "back": "Pacing. 100 questions in 115 minutes is 69 seconds each. Flag anything over 90 seconds and move.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-trap-016",
    "examId": "snowpro-c03",
    "domainId": "d3",
    "type": "trap",
    "front": "⚠️ Why candidates fail #9: Stage syntax: @~ user, @%t table, @name named.",
    "back": "Stage syntax: @~ user, @%t table, @name named. Know the symbols cold.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-trap-017",
    "examId": "snowpro-c03",
    "domainId": null,
    "type": "trap",
    "front": "⚠️ Why candidates fail #10: Skipping the sample questions in the official study guide PDF — they signal the exact phrasing you will see.",
    "back": "Skipping the sample questions in the official study guide PDF — they signal the exact phrasing you will see.",
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  }
];
