// GENERATED by scripts/migration/gen-content.mjs — 2026-08-17
// Source: snowpro-c03-guide MC+MC_EXTRA (133 items; explanations justify correct answer only → distractorRationale:false)
// Do not hand-edit content items: regenerate, or record any manual edit in MIGRATION_NOTES.md.
import type { Question } from "../../schema";

export const questions: Question[] = [
  {
    "id": "snowpro-c03-q-d1-001",
    "examId": "snowpro-c03",
    "domainId": "d1",
    "question": "Which Snowflake layer performs query parsing, optimization, metadata management, and authentication?",
    "options": [
      "Database Storage",
      "Virtual Warehouse (Compute)",
      "Cloud Services",
      "Cloud provider IAM"
    ],
    "correctIndex": 2,
    "explanation": "Cloud Services is the brain: auth, metadata, parsing, optimization, access control. Fully managed and stateless.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d1-002",
    "examId": "snowpro-c03",
    "domainId": "d1",
    "question": "Micro-partitions are approximately what size (uncompressed)?",
    "options": [
      "1–16 MB",
      "50–500 MB",
      "1–2 GB",
      "Fixed 128 MB"
    ],
    "correctIndex": 1,
    "explanation": "50–500 MB uncompressed, stored compressed, columnar, and immutable.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d1-003",
    "examId": "snowpro-c03",
    "domainId": "d1",
    "question": "Materialized Views and Multi-Cluster Warehouses first appear in which edition?",
    "options": [
      "Standard",
      "Enterprise",
      "Business Critical",
      "VPS"
    ],
    "correctIndex": 1,
    "explanation": "Enterprise also adds up to 90-day Time Travel and Search Optimization. Memorize the Enterprise list.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d1-004",
    "examId": "snowpro-c03",
    "domainId": "d1",
    "question": "Tri-Secret Secure requires at minimum which edition?",
    "options": [
      "Standard",
      "Enterprise",
      "Business Critical",
      "Any edition"
    ],
    "correctIndex": 2,
    "explanation": "Business Critical: Tri-Secret Secure, PrivateLink, HIPAA/PCI, failover groups.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d1-005",
    "examId": "snowpro-c03",
    "domainId": "d1",
    "question": "Which table type has up to 1 day of Time Travel and no Fail-safe, at lower storage cost?",
    "options": [
      "Permanent",
      "Transient",
      "External",
      "Iceberg"
    ],
    "correctIndex": 1,
    "explanation": "Transient trades Fail-safe away for cheaper storage. Classic exam distinction.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d1-006",
    "examId": "snowpro-c03",
    "domainId": "d1",
    "question": "A temporary table persists until…",
    "options": [
      "Explicitly dropped",
      "The warehouse suspends",
      "The session ends",
      "Time Travel expires"
    ],
    "correctIndex": 2,
    "explanation": "Temporary tables are session-scoped and vanish at session end.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d1-007",
    "examId": "snowpro-c03",
    "domainId": "d1",
    "question": "A Dynamic Table refreshes based on…",
    "options": [
      "A cron schedule you define",
      "Its TARGET_LAG setting",
      "Stream offsets",
      "Manual REFRESH only"
    ],
    "correctIndex": 1,
    "explanation": "You declare the target state and a TARGET_LAG; Snowflake orchestrates the refresh.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d1-008",
    "examId": "snowpro-c03",
    "domainId": "d1",
    "question": "Apache Iceberg tables in Snowflake primarily provide…",
    "options": [
      "Faster caching",
      "Open table format interoperability",
      "Row-store transactions",
      "Cheaper Fail-safe"
    ],
    "correctIndex": 1,
    "explanation": "Iceberg is about open-format interop, with Snowflake-managed or external catalogs. New in C03.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d1-009",
    "examId": "snowpro-c03",
    "domainId": "d1",
    "question": "Which Cortex service answers natural-language questions over structured tables?",
    "options": [
      "Cortex Search",
      "Cortex Analyst",
      "Document AI",
      "EMBED_TEXT"
    ],
    "correctIndex": 1,
    "explanation": "Analyst = text-to-SQL over structured data. Search = RAG over unstructured docs. The exam swaps them.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d1-010",
    "examId": "snowpro-c03",
    "domainId": "d1",
    "question": "Which Cortex service returns relevance-ranked chunks from unstructured documents?",
    "options": [
      "Cortex Analyst",
      "Cortex Search",
      "SUMMARIZE",
      "Snowflake ML"
    ],
    "correctIndex": 1,
    "explanation": "Cortex Search powers RAG over documents. Do not confuse with Analyst.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d1-011",
    "examId": "snowpro-c03",
    "domainId": "d1",
    "question": "Document AI is used to…",
    "options": [
      "Generate SQL from prompts",
      "Extract structured JSON from PDFs and images",
      "Mask documents",
      "Host Streamlit apps"
    ],
    "correctIndex": 1,
    "explanation": "Invoice parsing and form extraction are the canonical use cases.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d1-012",
    "examId": "snowpro-c03",
    "domainId": "d1",
    "question": "Git integration in Snowflake lets you…",
    "options": [
      "Version-control micro-partitions",
      "Connect a repo as a database object and execute files from it",
      "Replace Time Travel",
      "Deploy warehouses from CI"
    ],
    "correctIndex": 1,
    "explanation": "GitHub / GitLab / Bitbucket / Azure DevOps repos become Snowflake objects; Workspaces can fetch and run files.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d1-013",
    "examId": "snowpro-c03",
    "domainId": "d1",
    "question": "Hybrid tables (Unistore) are designed for…",
    "options": [
      "Archival storage",
      "Transactional row-store workloads",
      "External data lakes",
      "Semi-structured data only"
    ],
    "correctIndex": 1,
    "explanation": "Unistore brings OLTP-style workloads onto the same platform.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d1-014",
    "examId": "snowpro-c03",
    "domainId": "d1",
    "question": "Each warehouse size step (XS→S→M→…) roughly does what to credits per hour?",
    "options": [
      "Adds 1 credit",
      "Doubles them",
      "Halves them",
      "No change"
    ],
    "correctIndex": 1,
    "explanation": "XS=1, S=2, M=4, L=8, XL=16… doubling each step, billed per second with a 60s minimum.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d1-015",
    "examId": "snowpro-c03",
    "domainId": "d1",
    "question": "Snowpark lets you…",
    "options": [
      "Export data to Spark clusters",
      "Run Python/Java/Scala pushed down inside Snowflake",
      "Bypass RBAC for data science",
      "Query without a warehouse"
    ],
    "correctIndex": 1,
    "explanation": "DataFrame code executes in Snowflake compute; data never leaves the platform.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d2-001",
    "examId": "snowpro-c03",
    "domainId": "d2",
    "question": "In Snowflake RBAC, privileges are granted to…",
    "options": [
      "Users directly",
      "Roles only",
      "Warehouses",
      "Sessions"
    ],
    "correctIndex": 1,
    "explanation": "Never to users. Users get roles; roles can be granted to roles (inheritance).",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d2-002",
    "examId": "snowpro-c03",
    "domainId": "d2",
    "question": "Best practice: custom roles for creating databases and warehouses roll up under…",
    "options": [
      "ACCOUNTADMIN",
      "SECURITYADMIN",
      "SYSADMIN",
      "PUBLIC"
    ],
    "correctIndex": 2,
    "explanation": "Build the custom hierarchy below SYSADMIN; keep ACCOUNTADMIN rarely used.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d2-003",
    "examId": "snowpro-c03",
    "domainId": "d2",
    "question": "Which system role creates users and roles and is a child of SECURITYADMIN?",
    "options": [
      "USERADMIN",
      "ORGADMIN",
      "SYSADMIN",
      "PUBLIC"
    ],
    "correctIndex": 0,
    "explanation": "USERADMIN handles user/role creation; SECURITYADMIN manages grants globally.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d2-004",
    "examId": "snowpro-c03",
    "domainId": "d2",
    "question": "Does ACCOUNTADMIN automatically inherit custom roles?",
    "options": [
      "Yes, always",
      "Only in Enterprise",
      "No — only if granted",
      "Only via secondary roles"
    ],
    "correctIndex": 2,
    "explanation": "A top trap: custom roles must be granted up the hierarchy to be visible.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d2-005",
    "examId": "snowpro-c03",
    "domainId": "d2",
    "question": "Trust Center provides…",
    "options": [
      "A data catalog",
      "A security posture dashboard (MFA coverage, network policies, risky configs)",
      "Cost forecasts",
      "Query tuning hints"
    ],
    "correctIndex": 1,
    "explanation": "New in C03. Expect at least one question on what it surfaces.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d2-006",
    "examId": "snowpro-c03",
    "domainId": "d2",
    "question": "A dynamic data masking policy typically decides what to return based on…",
    "options": [
      "Warehouse size",
      "CURRENT_ROLE() at query time",
      "Table type",
      "Time of day"
    ],
    "correctIndex": 1,
    "explanation": "Policies evaluate context like current role and return masked or clear values per query.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d2-007",
    "examId": "snowpro-c03",
    "domainId": "d2",
    "question": "Row access policies enforce…",
    "options": [
      "Column encryption",
      "Row-level filtering by role or attribute",
      "Network isolation",
      "Share revocation"
    ],
    "correctIndex": 1,
    "explanation": "Row-level security; masking policies handle columns.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d2-008",
    "examId": "snowpro-c03",
    "domainId": "d2",
    "question": "A resource monitor set to \"suspend immediately\" will…",
    "options": [
      "Finish running queries first",
      "Kill running queries and suspend",
      "Only notify admins",
      "Resize the warehouse"
    ],
    "correctIndex": 1,
    "explanation": "\"Suspend\" lets queries finish; \"suspend immediate\" cancels them. Know both.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d2-009",
    "examId": "snowpro-c03",
    "domainId": "d2",
    "question": "Key-pair authentication is most commonly required for…",
    "options": [
      "Snowsight logins",
      "Service accounts and Snowpipe REST calls",
      "Reader accounts",
      "Marketplace listings"
    ],
    "correctIndex": 1,
    "explanation": "Programmatic access paths lean on key-pair auth.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d2-010",
    "examId": "snowpro-c03",
    "domainId": "d2",
    "question": "Network policies control access by…",
    "options": [
      "Role hierarchy",
      "IP allowlists and blocklists",
      "Warehouse tags",
      "Edition"
    ],
    "correctIndex": 1,
    "explanation": "Applied at account or user level; private connectivity goes further via PrivateLink equivalents.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d3-001",
    "examId": "snowpro-c03",
    "domainId": "d3",
    "question": "The stage referenced as @~ is a…",
    "options": [
      "Table stage",
      "User stage",
      "Named internal stage",
      "External stage"
    ],
    "correctIndex": 1,
    "explanation": "@~ user, @%tablename table, @name named. Know the symbols cold.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d3-002",
    "examId": "snowpro-c03",
    "domainId": "d3",
    "question": "The stage referenced as @%orders is a…",
    "options": [
      "User stage",
      "Named external stage",
      "Table stage for ORDERS",
      "Directory table"
    ],
    "correctIndex": 2,
    "explanation": "@% prefixes a table stage tied to that one table.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d3-003",
    "examId": "snowpro-c03",
    "domainId": "d3",
    "question": "Which is NOT a valid COPY INTO ON_ERROR option?",
    "options": [
      "CONTINUE",
      "SKIP_FILE",
      "ABORT_STATEMENT",
      "ROLLBACK_ROW"
    ],
    "correctIndex": 3,
    "explanation": "Valid modes: CONTINUE, SKIP_FILE, SKIP_FILE_n%, ABORT_STATEMENT.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d3-004",
    "examId": "snowpro-c03",
    "domainId": "d3",
    "question": "Snowpipe delivers data with what typical latency?",
    "options": [
      "Sub-second",
      "Seconds",
      "Minutes (micro-batch)",
      "Hourly"
    ],
    "correctIndex": 2,
    "explanation": "Snowpipe is file-based micro-batch. Row-level seconds latency is Snowpipe Streaming.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d3-005",
    "examId": "snowpro-c03",
    "domainId": "d3",
    "question": "Snowpipe Streaming ingests via…",
    "options": [
      "Cloud event notifications",
      "The Snowflake Ingest SDK, row by row",
      "COPY INTO on a schedule",
      "External functions"
    ],
    "correctIndex": 1,
    "explanation": "Different SDK, different latency, different pricing than classic Snowpipe.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d3-006",
    "examId": "snowpro-c03",
    "domainId": "d3",
    "question": "A storage integration exists to…",
    "options": [
      "Encrypt stages",
      "Grant IAM-based access to external stages without embedding credentials",
      "Compress files",
      "Schedule loads"
    ],
    "correctIndex": 1,
    "explanation": "It delegates cloud IAM trust so no keys live in Snowflake objects.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d3-007",
    "examId": "snowpro-c03",
    "domainId": "d3",
    "question": "The recommended file format for bulk load performance is…",
    "options": [
      "CSV",
      "XML",
      "Parquet",
      "Avro"
    ],
    "correctIndex": 2,
    "explanation": "Columnar Parquet loads fastest among the supported formats.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d3-008",
    "examId": "snowpro-c03",
    "domainId": "d3",
    "question": "A stream on a table captures…",
    "options": [
      "Query history",
      "Inserts, updates, and deletes (CDC)",
      "Schema changes",
      "Grants"
    ],
    "correctIndex": 1,
    "explanation": "Streams expose change sets; pair with tasks for incremental pipelines.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d3-009",
    "examId": "snowpro-c03",
    "domainId": "d3",
    "question": "Tasks can be triggered by…",
    "options": [
      "A cron schedule or a predecessor task",
      "Warehouse resume",
      "Stage file arrival",
      "Share consumption"
    ],
    "correctIndex": 0,
    "explanation": "Cron or AFTER another task — enabling DAGs.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d3-010",
    "examId": "snowpro-c03",
    "domainId": "d3",
    "question": "To unload data you run…",
    "options": [
      "GET",
      "COPY INTO @stage",
      "EXPORT TABLE",
      "UNLOAD TO"
    ],
    "correctIndex": 1,
    "explanation": "Same COPY INTO command, direction reversed: table → stage.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d4-001",
    "examId": "snowpro-c03",
    "domainId": "d4",
    "question": "The result cache lives where and lasts how long?",
    "options": [
      "Warehouse SSD, until suspend",
      "Cloud Services, 24h (extended on reuse up to 31 days)",
      "Client driver, per session",
      "Storage layer, forever"
    ],
    "correctIndex": 1,
    "explanation": "Account-wide exact-result reuse — no warehouse needed to serve a hit.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d4-002",
    "examId": "snowpro-c03",
    "domainId": "d4",
    "question": "Which query can be answered from the metadata cache without a running warehouse?",
    "options": [
      "SELECT * with a filter",
      "SELECT COUNT(*) FROM t",
      "A windowed aggregate",
      "A join"
    ],
    "correctIndex": 1,
    "explanation": "COUNT / MIN / MAX style stats come straight from metadata.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d4-003",
    "examId": "snowpro-c03",
    "domainId": "d4",
    "question": "The warehouse data cache is lost when…",
    "options": [
      "The result cache expires",
      "The warehouse suspends",
      "A new query runs",
      "Clustering runs"
    ],
    "correctIndex": 1,
    "explanation": "The auto-suspend tension: saving credits drops the local SSD cache.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d4-004",
    "examId": "snowpro-c03",
    "domainId": "d4",
    "question": "\"Bytes spilled to remote storage\" in a Query Profile means…",
    "options": [
      "Bad pruning",
      "The warehouse is undersized — scale up",
      "Too many clusters",
      "A caching bug"
    ],
    "correctIndex": 1,
    "explanation": "Spilling = memory pressure. Scale UP for single heavy queries.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d4-005",
    "examId": "snowpro-c03",
    "domainId": "d4",
    "question": "Many users queuing on a dashboard warehouse calls for…",
    "options": [
      "A bigger size",
      "Scaling out with a Multi-Cluster Warehouse",
      "More clustering keys",
      "Result cache tuning"
    ],
    "correctIndex": 1,
    "explanation": "Concurrency = scale OUT (Enterprise+). Complexity = scale UP.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d4-006",
    "examId": "snowpro-c03",
    "domainId": "d4",
    "question": "QUALIFY is used to…",
    "options": [
      "Filter on window function results",
      "Rank stages",
      "Validate loads",
      "Grant privileges"
    ],
    "correctIndex": 0,
    "explanation": "It is HAVING for window functions — a Snowflake SQL extension.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d4-007",
    "examId": "snowpro-c03",
    "domainId": "d4",
    "question": "Clustering keys are appropriate for…",
    "options": [
      "Every table",
      "Small lookup tables",
      "Large (~1 TB+) tables with selective filter columns",
      "Temporary tables"
    ],
    "correctIndex": 2,
    "explanation": "Clustering small tables wastes credits. Automatic Clustering bills as it re-sorts.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d4-008",
    "examId": "snowpro-c03",
    "domainId": "d4",
    "question": "Query Acceleration Service does what?",
    "options": [
      "Caches results longer",
      "Offloads scan-heavy work to shared serverless compute",
      "Rewrites SQL",
      "Pre-warms warehouses"
    ],
    "correctIndex": 1,
    "explanation": "New in C03: bursts of extra compute for outlier scans without resizing.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d4-009",
    "examId": "snowpro-c03",
    "domainId": "d4",
    "question": "LATERAL FLATTEN is used to…",
    "options": [
      "Pivot columns",
      "Explode nested arrays in semi-structured data into rows",
      "Merge tables",
      "Mask JSON"
    ],
    "correctIndex": 1,
    "explanation": "The core tool for unpacking VARIANT arrays and objects.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d4-010",
    "examId": "snowpro-c03",
    "domainId": "d4",
    "question": "The :: operator in Snowflake SQL performs…",
    "options": [
      "Path navigation",
      "Casting",
      "Concatenation",
      "Masking"
    ],
    "correctIndex": 1,
    "explanation": "payload:items[0].sku::STRING — colon paths navigate, :: casts.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d4-011",
    "examId": "snowpro-c03",
    "domainId": "d4",
    "question": "Search Optimization Service is best for…",
    "options": [
      "Full scans",
      "Selective point-lookup queries (Enterprise+)",
      "Loading",
      "Cloning"
    ],
    "correctIndex": 1,
    "explanation": "A persistent search access path for needle-in-haystack lookups.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d5-001",
    "examId": "snowpro-c03",
    "domainId": "d5",
    "question": "Maximum Time Travel for a permanent table on Enterprise edition is…",
    "options": [
      "1 day",
      "7 days",
      "30 days",
      "90 days"
    ],
    "correctIndex": 3,
    "explanation": "Standard caps at 1 day; Enterprise+ extends to 90 for permanent tables.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d5-002",
    "examId": "snowpro-c03",
    "domainId": "d5",
    "question": "Fail-safe is…",
    "options": [
      "7 days, user-accessible",
      "7 days, recoverable only via Snowflake support",
      "90 days, admin-accessible",
      "Optional per table"
    ],
    "correctIndex": 1,
    "explanation": "User-facing recovery is Time Travel; Fail-safe is a support-ticket safety net.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d5-003",
    "examId": "snowpro-c03",
    "domainId": "d5",
    "question": "A consumer account is in a different region than the provider. A direct share…",
    "options": [
      "Works normally",
      "Requires replication first or a Marketplace listing",
      "Only needs ORGADMIN",
      "Works if both are Enterprise"
    ],
    "correctIndex": 1,
    "explanation": "Direct shares are same-region. Cross-region needs replication or a listing.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d5-004",
    "examId": "snowpro-c03",
    "domainId": "d5",
    "question": "A reader account is…",
    "options": [
      "Any trial account",
      "A provider-managed account for consumers without Snowflake",
      "Read replica of a database",
      "A Marketplace tier"
    ],
    "correctIndex": 1,
    "explanation": "The provider provisions and pays for it; the consumer needs no Snowflake contract.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d5-005",
    "examId": "snowpro-c03",
    "domainId": "d5",
    "question": "Zero-copy cloning consumes additional storage…",
    "options": [
      "Immediately, full copy",
      "Only as cloned data diverges from the source",
      "Never",
      "After 24 hours"
    ],
    "correctIndex": 1,
    "explanation": "It is a metadata operation; storage grows only with divergence.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d5-006",
    "examId": "snowpro-c03",
    "domainId": "d5",
    "question": "UNDROP works…",
    "options": [
      "Anytime",
      "Within the Time Travel retention window",
      "Within Fail-safe",
      "Only for schemas"
    ],
    "correctIndex": 1,
    "explanation": "Once Time Travel lapses into Fail-safe, only support can recover it.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d1-016",
    "examId": "snowpro-c03",
    "domainId": "d1",
    "question": "Snowflake runs natively on which cloud providers?",
    "options": [
      "AWS only",
      "AWS and Azure",
      "AWS, Azure, and Google Cloud",
      "Any private data center"
    ],
    "correctIndex": 2,
    "explanation": "Snowflake is fully managed on AWS, Azure, and GCP; an account lives in one region of one cloud.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d1-017",
    "examId": "snowpro-c03",
    "domainId": "d1",
    "question": "Cloud Services compute is billed…",
    "options": [
      "Always, per query",
      "Only when daily usage exceeds 10% of daily warehouse credit usage",
      "Never",
      "Per user per month"
    ],
    "correctIndex": 1,
    "explanation": "The 10% daily adjustment: most accounts pay nothing extra for Cloud Services.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d1-018",
    "examId": "snowpro-c03",
    "domainId": "d1",
    "question": "How is data physically stored in the storage layer?",
    "options": [
      "Row-oriented, mutable files",
      "Compressed, columnar, immutable micro-partitions",
      "Raw CSV",
      "Customer-managed buckets"
    ],
    "correctIndex": 1,
    "explanation": "Columnar + compressed + immutable enables pruning and zero-copy features.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d1-019",
    "examId": "snowpro-c03",
    "domainId": "d1",
    "question": "Because micro-partitions are immutable, an UPDATE…",
    "options": [
      "Edits data in place",
      "Writes new micro-partitions and retires old ones",
      "Requires a table rebuild",
      "Locks the table"
    ],
    "correctIndex": 1,
    "explanation": "Old versions back Time Travel; new partitions carry the change.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d1-020",
    "examId": "snowpro-c03",
    "domainId": "d1",
    "question": "The default auto-suspend for a new warehouse created in Snowsight is…",
    "options": [
      "60 seconds",
      "5 minutes",
      "10 minutes",
      "Never"
    ],
    "correctIndex": 2,
    "explanation": "600 seconds by default; it can be lowered to 60 seconds.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d1-021",
    "examId": "snowpro-c03",
    "domainId": "d1",
    "question": "A resumed warehouse bills a minimum of…",
    "options": [
      "1 second",
      "60 seconds",
      "5 minutes",
      "1 hour"
    ],
    "correctIndex": 1,
    "explanation": "Per-second billing with a 60-second minimum on each resume.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d1-022",
    "examId": "snowpro-c03",
    "domainId": "d1",
    "question": "Multi-cluster warehouses run in which two modes?",
    "options": [
      "Burst and steady",
      "Maximized and Auto-scale",
      "Primary and replica",
      "Hot and cold"
    ],
    "correctIndex": 1,
    "explanation": "Maximized runs all clusters always; Auto-scale adds and removes clusters between min and max.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d1-023",
    "examId": "snowpro-c03",
    "domainId": "d1",
    "question": "Auto-scale MCWs choose between which scaling policies?",
    "options": [
      "Fast / Slow",
      "Standard / Economy",
      "Eager / Lazy",
      "Linear / Exponential"
    ],
    "correctIndex": 1,
    "explanation": "Standard favors starting clusters to kill queuing; Economy conserves credits by letting queries queue longer.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d1-024",
    "examId": "snowpro-c03",
    "domainId": "d1",
    "question": "A materialized view can be defined on…",
    "options": [
      "Any join of tables",
      "A single table, no joins",
      "Only external tables",
      "Only secure views"
    ],
    "correctIndex": 1,
    "explanation": "MVs are restricted to a single table with no joins; maintenance is serverless and billed.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d1-025",
    "examId": "snowpro-c03",
    "domainId": "d1",
    "question": "Secure views are required when…",
    "options": [
      "Using Time Travel",
      "Sharing views with consumer accounts",
      "Querying VARIANT",
      "Using QUALIFY"
    ],
    "correctIndex": 1,
    "explanation": "Sharing requires secure views/UDFs so consumers cannot see the definition or exploit optimizations to infer hidden data.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d1-026",
    "examId": "snowpro-c03",
    "domainId": "d1",
    "question": "A directory table is…",
    "options": [
      "A schema listing",
      "A catalog of files on a stage, queryable with SQL",
      "A clone of INFORMATION_SCHEMA",
      "A hidden system table"
    ],
    "correctIndex": 1,
    "explanation": "Directory tables expose file-level metadata on stages — the basis for unstructured data work.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d1-027",
    "examId": "snowpro-c03",
    "domainId": "d1",
    "question": "Snowpark-optimized warehouses exist for…",
    "options": [
      "Cheaper BI dashboards",
      "Memory-intensive ML and Snowpark workloads",
      "Faster COPY INTO",
      "Serverless tasks"
    ],
    "correctIndex": 1,
    "explanation": "They provide far more memory per node for training-style workloads.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d1-028",
    "examId": "snowpro-c03",
    "domainId": "d1",
    "question": "All data at rest in Snowflake is…",
    "options": [
      "Optionally encrypted",
      "Always encrypted with AES-256 under a hierarchical key model",
      "Encrypted only in Business Critical",
      "Encrypted by the customer"
    ],
    "correctIndex": 1,
    "explanation": "Always-on encryption; keys auto-rotate every 30 days, with annual rekeying available.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d1-029",
    "examId": "snowpro-c03",
    "domainId": "d1",
    "question": "An organization in Snowflake…",
    "options": [
      "Is one account",
      "Groups multiple accounts under ORGADMIN",
      "Is a billing-only concept",
      "Requires VPS"
    ],
    "correctIndex": 1,
    "explanation": "ORGADMIN manages accounts, and organization-level usage views span them.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d1-030",
    "examId": "snowpro-c03",
    "domainId": "d1",
    "question": "The default Time Travel retention on a new permanent table is…",
    "options": [
      "0 days",
      "1 day",
      "7 days",
      "90 days"
    ],
    "correctIndex": 1,
    "explanation": "1 day everywhere by default; DATA_RETENTION_TIME_IN_DAYS raises it up to 90 on Enterprise+.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d1-031",
    "examId": "snowpro-c03",
    "domainId": "d1",
    "question": "Cortex COMPLETE does what?",
    "options": [
      "Autocompletes SQL in Snowsight",
      "Runs an LLM completion over text via SQL",
      "Finishes failed loads",
      "Completes missing rows"
    ],
    "correctIndex": 1,
    "explanation": "SNOWFLAKE.CORTEX.COMPLETE(model, prompt) — LLM inference in a SQL function.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d1-032",
    "examId": "snowpro-c03",
    "domainId": "d1",
    "question": "EMBED_TEXT functions return…",
    "options": [
      "Summaries",
      "Vector embeddings for semantic search",
      "Translations",
      "Masked text"
    ],
    "correctIndex": 1,
    "explanation": "Embeddings power vector similarity and RAG patterns.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d1-033",
    "examId": "snowpro-c03",
    "domainId": "d1",
    "question": "Streamlit in Snowflake means apps…",
    "options": [
      "Run on your laptop",
      "Run inside the Snowflake account with its RBAC",
      "Require external hosting",
      "Are read-only"
    ],
    "correctIndex": 1,
    "explanation": "Apps deploy next to the data and inherit Snowflake governance.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d1-034",
    "examId": "snowpro-c03",
    "domainId": "d1",
    "question": "Which interface is the modern command-line client?",
    "options": [
      "Snowsight",
      "Snowflake CLI (with SnowSQL as legacy)",
      "SnowShell",
      "sfctl"
    ],
    "correctIndex": 1,
    "explanation": "Snowflake CLI is the newer CLI; SnowSQL remains as the legacy client.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d1-035",
    "examId": "snowpro-c03",
    "domainId": "d1",
    "question": "Hybrid tables differ from standard tables because they…",
    "options": [
      "Are columnar only",
      "Use a row store with indexes for fast single-row operations",
      "Skip Cloud Services",
      "Cannot be queried with SQL"
    ],
    "correctIndex": 1,
    "explanation": "Unistore: OLTP-style point reads/writes plus analytical access on one platform.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d2-011",
    "examId": "snowpro-c03",
    "domainId": "d2",
    "question": "SECURITYADMIN automatically inherits which role?",
    "options": [
      "SYSADMIN",
      "USERADMIN",
      "ORGADMIN",
      "ACCOUNTADMIN"
    ],
    "correctIndex": 1,
    "explanation": "USERADMIN is a child of SECURITYADMIN in the default hierarchy.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d2-012",
    "examId": "snowpro-c03",
    "domainId": "d2",
    "question": "To let a role automatically receive privileges on tables created later in a schema, use…",
    "options": [
      "GRANT ALL",
      "Future grants (GRANT … ON FUTURE TABLES IN SCHEMA …)",
      "Ownership transfer",
      "Secondary roles"
    ],
    "correctIndex": 1,
    "explanation": "Future grants apply to objects that do not exist yet — a favorite exam nuance.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d2-013",
    "examId": "snowpro-c03",
    "domainId": "d2",
    "question": "Every securable object has…",
    "options": [
      "Multiple owning roles",
      "Exactly one owning role",
      "No owner until granted",
      "ACCOUNTADMIN as owner"
    ],
    "correctIndex": 1,
    "explanation": "Ownership is held by a single role and can be transferred.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d2-014",
    "examId": "snowpro-c03",
    "domainId": "d2",
    "question": "Secondary roles allow…",
    "options": [
      "Bypassing RBAC",
      "A session to use privileges of multiple granted roles at once",
      "Anonymous queries",
      "Cross-account access"
    ],
    "correctIndex": 1,
    "explanation": "USE SECONDARY ROLES ALL activates the union of the user’s granted roles alongside the primary.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d2-015",
    "examId": "snowpro-c03",
    "domainId": "d2",
    "question": "ACCOUNT_USAGE views differ from INFORMATION_SCHEMA because they…",
    "options": [
      "Are real-time with short history",
      "Have latency (minutes to hours) but ~365 days of history",
      "Are per-warehouse",
      "Require VPS"
    ],
    "correctIndex": 1,
    "explanation": "INFORMATION_SCHEMA is low-latency with shorter retention; ACCOUNT_USAGE trades latency for a year of history.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d2-016",
    "examId": "snowpro-c03",
    "domainId": "d2",
    "question": "When both account-level and user-level network policies exist…",
    "options": [
      "Account wins",
      "User-level takes precedence for that user",
      "Both must pass",
      "Policies merge"
    ],
    "correctIndex": 1,
    "explanation": "The user-level policy overrides the account-level one for that user.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d2-017",
    "examId": "snowpro-c03",
    "domainId": "d2",
    "question": "SCIM integration is used for…",
    "options": [
      "Row security",
      "Automated user and role provisioning from an identity provider",
      "Masking",
      "Cost alerts"
    ],
    "correctIndex": 1,
    "explanation": "Okta / Entra ID push users and groups into Snowflake via SCIM.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d2-018",
    "examId": "snowpro-c03",
    "domainId": "d2",
    "question": "Tag-based masking means…",
    "options": [
      "Tags encrypt columns",
      "A masking policy attached to a tag applies wherever the tag is set",
      "Tags hide tables",
      "Only tagged users see data"
    ],
    "correctIndex": 1,
    "explanation": "Set the tag on many columns; the policy follows the tag — governance at scale.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d2-019",
    "examId": "snowpro-c03",
    "domainId": "d2",
    "question": "Automatic classification does what?",
    "options": [
      "Indexes tables",
      "Detects and tags semantic categories like PII",
      "Compresses data",
      "Ranks queries"
    ],
    "correctIndex": 1,
    "explanation": "Classification suggests semantic and privacy categories you can apply as tags.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d2-020",
    "examId": "snowpro-c03",
    "domainId": "d2",
    "question": "A session policy controls…",
    "options": [
      "Warehouse size",
      "Idle session timeout behavior",
      "Role hierarchy",
      "Share access"
    ],
    "correctIndex": 1,
    "explanation": "Session policies set idle timeouts for the UI and clients.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d2-021",
    "examId": "snowpro-c03",
    "domainId": "d2",
    "question": "Storage is billed…",
    "options": [
      "Per credit",
      "Flat rate per compressed TB per month",
      "Per micro-partition",
      "Per query"
    ],
    "correctIndex": 1,
    "explanation": "Compute is credits; storage is a flat monthly rate on the compressed footprint (plus Time Travel/Fail-safe copies).",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d2-022",
    "examId": "snowpro-c03",
    "domainId": "d2",
    "question": "Serverless features (Snowpipe, automatic clustering, MV maintenance, serverless tasks) are billed…",
    "options": [
      "Through your warehouse",
      "As separate Snowflake-managed compute at feature-specific credit rates",
      "Free of charge",
      "Storage only"
    ],
    "correctIndex": 1,
    "explanation": "They consume credits without any user-run warehouse.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d2-023",
    "examId": "snowpro-c03",
    "domainId": "d2",
    "question": "A resource monitor can be assigned to…",
    "options": [
      "Users",
      "The account or specific warehouses",
      "Databases",
      "Roles"
    ],
    "correctIndex": 1,
    "explanation": "Quotas apply account-wide or to a set of warehouses.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d2-024",
    "examId": "snowpro-c03",
    "domainId": "d2",
    "question": "MFA in Snowflake is delivered through…",
    "options": [
      "Any TOTP app only",
      "Built-in Duo integration",
      "SMS only",
      "Hardware keys only"
    ],
    "correctIndex": 1,
    "explanation": "Duo push/passcodes back the native MFA; SSO can layer IdP-side factors too.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d2-025",
    "examId": "snowpro-c03",
    "domainId": "d2",
    "question": "PrivateLink-style private connectivity requires at least…",
    "options": [
      "Standard",
      "Enterprise",
      "Business Critical",
      "Any edition with a support ticket"
    ],
    "correctIndex": 2,
    "explanation": "Private connectivity is a Business Critical capability.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d3-011",
    "examId": "snowpro-c03",
    "domainId": "d3",
    "question": "PUT is used to…",
    "options": [
      "Download files from a stage",
      "Upload local files to an internal stage",
      "Load a table",
      "Create a stage"
    ],
    "correctIndex": 1,
    "explanation": "PUT uploads via SnowSQL/CLI or drivers (not the Snowsight worksheet); GET downloads.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d3-012",
    "examId": "snowpro-c03",
    "domainId": "d3",
    "question": "GET is used to…",
    "options": [
      "Query a stage",
      "Download files from a stage to the local machine",
      "Fetch query results",
      "Read directory tables"
    ],
    "correctIndex": 1,
    "explanation": "The unload workflow: COPY INTO @stage, then GET.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d3-013",
    "examId": "snowpro-c03",
    "domainId": "d3",
    "question": "Bulk COPY load metadata (which files were loaded) is retained for…",
    "options": [
      "24 hours",
      "14 days",
      "64 days",
      "Forever"
    ],
    "correctIndex": 2,
    "explanation": "Within 64 days Snowflake skips already-loaded files to prevent duplicates.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d3-014",
    "examId": "snowpro-c03",
    "domainId": "d3",
    "question": "VALIDATION_MODE on COPY INTO lets you…",
    "options": [
      "Load faster",
      "Test files for errors without loading any data",
      "Skip file formats",
      "Validate grants"
    ],
    "correctIndex": 1,
    "explanation": "RETURN_ERRORS / RETURN_n_ROWS dry-run the load.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d3-015",
    "examId": "snowpro-c03",
    "domainId": "d3",
    "question": "MATCH_BY_COLUMN_NAME is useful when…",
    "options": [
      "Loading CSV by position",
      "Loading Parquet/JSON columns by name, case-insensitively if desired",
      "Unloading",
      "Renaming tables"
    ],
    "correctIndex": 1,
    "explanation": "Semi-structured and columnar formats can map to columns by name instead of position.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d3-016",
    "examId": "snowpro-c03",
    "domainId": "d3",
    "question": "The recommended file size for efficient bulk loading is roughly…",
    "options": [
      "1–10 KB",
      "100–250 MB compressed",
      "2–5 GB",
      "Exactly 16 MB"
    ],
    "correctIndex": 1,
    "explanation": "Split huge files and batch tiny ones toward 100–250 MB compressed for parallelism.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d3-017",
    "examId": "snowpro-c03",
    "domainId": "d3",
    "question": "Snowpipe avoids loading the same file twice by…",
    "options": [
      "Row hashing",
      "File-loading metadata tracked per pipe",
      "Locking the stage",
      "Checksums you provide"
    ],
    "correctIndex": 1,
    "explanation": "Pipes track loaded files, so re-copied files are skipped.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d3-018",
    "examId": "snowpro-c03",
    "domainId": "d3",
    "question": "An external table’s metadata can be kept current by…",
    "options": [
      "Re-creating it",
      "Auto-refresh via cloud event notifications or manual ALTER … REFRESH",
      "Snowpipe",
      "Cloning"
    ],
    "correctIndex": 1,
    "explanation": "Event notifications keep the file registry in sync with object storage.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d3-019",
    "examId": "snowpro-c03",
    "domainId": "d3",
    "question": "Which stream types exist?",
    "options": [
      "Standard, append-only, insert-only",
      "Fast and slow",
      "Delta and full",
      "Batch and streaming"
    ],
    "correctIndex": 0,
    "explanation": "Standard (full CDC), append-only (tables), insert-only (external tables).",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d3-020",
    "examId": "snowpro-c03",
    "domainId": "d3",
    "question": "A stream advances its offset when…",
    "options": [
      "You read it with SELECT",
      "Its rows are consumed in a DML statement (e.g., INSERT … SELECT FROM stream)",
      "The task tree ends",
      "The warehouse suspends"
    ],
    "correctIndex": 1,
    "explanation": "SELECT alone does not consume; DML within a transaction moves the offset.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d3-021",
    "examId": "snowpro-c03",
    "domainId": "d3",
    "question": "A stream becomes stale when…",
    "options": [
      "The table is cloned",
      "It is not consumed within the source table’s retention window",
      "A task fails",
      "Its name is reused"
    ],
    "correctIndex": 1,
    "explanation": "Consume streams regularly or extend retention, or the change history ages out.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d3-022",
    "examId": "snowpro-c03",
    "domainId": "d3",
    "question": "In a task graph (DAG), which task has a schedule?",
    "options": [
      "Every task",
      "Only the root task",
      "Only leaf tasks",
      "None"
    ],
    "correctIndex": 1,
    "explanation": "Children run AFTER predecessors; only the root carries the cron/interval.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d3-023",
    "examId": "snowpro-c03",
    "domainId": "d3",
    "question": "Serverless tasks differ from user-managed tasks because they…",
    "options": [
      "Cannot be scheduled",
      "Use Snowflake-managed compute instead of your warehouse",
      "Run only hourly",
      "Skip error handling"
    ],
    "correctIndex": 1,
    "explanation": "Omit the WAREHOUSE parameter and Snowflake sizes compute for you.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d3-024",
    "examId": "snowpro-c03",
    "domainId": "d3",
    "question": "Which transformations are allowed inside a COPY INTO load?",
    "options": [
      "Any join",
      "Column reordering, casting, and selecting subsets (no joins)",
      "Window functions",
      "Stored procedure calls"
    ],
    "correctIndex": 1,
    "explanation": "Basic transformations only; heavier logic belongs post-load (ELT).",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d3-025",
    "examId": "snowpro-c03",
    "domainId": "d3",
    "question": "Supported unload formats are…",
    "options": [
      "CSV, JSON, Parquet",
      "XML and Avro",
      "ORC only",
      "Any format"
    ],
    "correctIndex": 0,
    "explanation": "Unloading writes delimited files, JSON, or Parquet; SINGLE=TRUE forces one file.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d3-026",
    "examId": "snowpro-c03",
    "domainId": "d3",
    "question": "The Kafka connector’s job is to…",
    "options": [
      "Query Kafka from SQL",
      "Land Kafka topic messages into Snowflake tables",
      "Replace Snowpipe Streaming",
      "Manage schemas"
    ],
    "correctIndex": 1,
    "explanation": "Topics map to tables; the connector handles ingestion.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d4-012",
    "examId": "snowpro-c03",
    "domainId": "d4",
    "question": "The result cache returns a previous result only if…",
    "options": [
      "The SQL text is similar",
      "The query is identical, underlying data is unchanged, and the role has the required privileges",
      "The same user runs it",
      "The warehouse is the same"
    ],
    "correctIndex": 1,
    "explanation": "Exact match + unchanged data + sufficient privileges (and reuse enabled).",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d4-013",
    "examId": "snowpro-c03",
    "domainId": "d4",
    "question": "SYSTEM$CLUSTERING_DEPTH returns…",
    "options": [
      "Partition count",
      "Average overlap depth — smaller means better clustered",
      "Credit cost",
      "Prune ratio"
    ],
    "correctIndex": 1,
    "explanation": "Depth measures micro-partition overlap for given columns; lower is better.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d4-014",
    "examId": "snowpro-c03",
    "domainId": "d4",
    "question": "Automatic Clustering compute is…",
    "options": [
      "Your warehouse",
      "Serverless, billed in credits as it re-sorts in the background",
      "Free",
      "Cloud Services"
    ],
    "correctIndex": 1,
    "explanation": "Another serverless meter — a reason not to cluster casually.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d4-015",
    "examId": "snowpro-c03",
    "domainId": "d4",
    "question": "Partition pruning relies on…",
    "options": [
      "Indexes",
      "Per-column min/max metadata on each micro-partition",
      "Statistics you gather",
      "Hints"
    ],
    "correctIndex": 1,
    "explanation": "Metadata lets Snowflake skip partitions that cannot match the predicate.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d4-016",
    "examId": "snowpro-c03",
    "domainId": "d4",
    "question": "CREATE TABLE t2 LIKE t1 produces…",
    "options": [
      "A zero-copy of the data",
      "An empty table with the same structure",
      "A view",
      "A share"
    ],
    "correctIndex": 1,
    "explanation": "LIKE copies structure only; CLONE copies data zero-copy.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d4-017",
    "examId": "snowpro-c03",
    "domainId": "d4",
    "question": "MERGE is used to…",
    "options": [
      "Combine warehouses",
      "Perform insert/update/delete in one statement based on a match condition",
      "Union tables",
      "Compact partitions"
    ],
    "correctIndex": 1,
    "explanation": "The upsert workhorse — also the pattern paired with streams.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d4-018",
    "examId": "snowpro-c03",
    "domainId": "d4",
    "question": "A UDF differs from a stored procedure because a UDF…",
    "options": [
      "Runs faster",
      "Returns a value usable inside SQL, while a procedure performs actions and is invoked with CALL",
      "Requires JavaScript",
      "Cannot take arguments"
    ],
    "correctIndex": 1,
    "explanation": "UDFs live in expressions; procedures orchestrate.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d4-019",
    "examId": "snowpro-c03",
    "domainId": "d4",
    "question": "A UDTF returns…",
    "options": [
      "A scalar",
      "A set of rows (a table)",
      "JSON only",
      "A file"
    ],
    "correctIndex": 1,
    "explanation": "Tabular UDFs are queried in the FROM clause.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d4-020",
    "examId": "snowpro-c03",
    "domainId": "d4",
    "question": "External functions call…",
    "options": [
      "Other UDFs",
      "Code outside Snowflake through an API integration (e.g., API Gateway to a Lambda)",
      "Snowpark",
      "Marketplace apps"
    ],
    "correctIndex": 1,
    "explanation": "API integrations broker the call to remote services.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d4-021",
    "examId": "snowpro-c03",
    "domainId": "d4",
    "question": "The maximum size of a single VARIANT value is…",
    "options": [
      "1 MB",
      "8 MB",
      "16 MB",
      "Unlimited"
    ],
    "correctIndex": 2,
    "explanation": "16 MB per value — a classic exam number.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d4-022",
    "examId": "snowpro-c03",
    "domainId": "d4",
    "question": "STRIP_OUTER_ARRAY = TRUE on a JSON load…",
    "options": [
      "Removes nulls",
      "Loads each element of a top-level array as its own row",
      "Flattens all nesting",
      "Validates schema"
    ],
    "correctIndex": 1,
    "explanation": "Without it a whole top-level array can land as one giant VARIANT (and can hit the 16 MB cap).",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d4-023",
    "examId": "snowpro-c03",
    "domainId": "d4",
    "question": "To sample roughly 10% of a table’s rows you use…",
    "options": [
      "LIMIT 10",
      "SELECT … SAMPLE (10)",
      "TOP 10%",
      "WHERE RANDOM()<10"
    ],
    "correctIndex": 1,
    "explanation": "SAMPLE/TABLESAMPLE draws probabilistic samples cheaply.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d4-024",
    "examId": "snowpro-c03",
    "domainId": "d4",
    "question": "Search Optimization Service primarily accelerates…",
    "options": [
      "Full-table aggregations",
      "Highly selective equality and IN lookups",
      "Sorting",
      "Loads"
    ],
    "correctIndex": 1,
    "explanation": "Point-lookup access paths on large tables (Enterprise+), billed serverlessly.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d4-025",
    "examId": "snowpro-c03",
    "domainId": "d4",
    "question": "MAX_CONCURRENCY_LEVEL on a warehouse controls…",
    "options": [
      "User count",
      "How many queries run concurrently per cluster before queuing/QAS kicks in",
      "Cluster count",
      "Credits"
    ],
    "correctIndex": 1,
    "explanation": "Lowering it dedicates more resources per query; queuing spills to added clusters in an MCW.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d4-026",
    "examId": "snowpro-c03",
    "domainId": "d4",
    "question": "STATEMENT_TIMEOUT_IN_SECONDS does what?",
    "options": [
      "Suspends warehouses",
      "Cancels statements that run longer than the limit",
      "Delays queries",
      "Rate-limits users"
    ],
    "correctIndex": 1,
    "explanation": "A guardrail parameter settable at account, warehouse, or session level.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d4-027",
    "examId": "snowpro-c03",
    "domainId": "d4",
    "question": "EXPLAIN differs from Query Profile because EXPLAIN…",
    "options": [
      "Shows runtime stats",
      "Shows the plan without executing; the profile shows actual execution",
      "Requires Enterprise",
      "Is graphical only"
    ],
    "correctIndex": 1,
    "explanation": "Plan vs actuals — use the profile to diagnose real behavior like spilling.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d4-028",
    "examId": "snowpro-c03",
    "domainId": "d4",
    "question": "OBJECT_CONSTRUCT is used to…",
    "options": [
      "Create tables",
      "Build a JSON-like object from key-value pairs in SQL",
      "Clone objects",
      "Grant privileges"
    ],
    "correctIndex": 1,
    "explanation": "Alongside ARRAY_AGG and ARRAY_CONSTRUCT for composing semi-structured output.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d4-029",
    "examId": "snowpro-c03",
    "domainId": "d4",
    "question": "Persisted query results can be reused for up to…",
    "options": [
      "24 hours flat",
      "31 days if re-accessed within each 24-hour window",
      "7 days",
      "1 hour"
    ],
    "correctIndex": 1,
    "explanation": "Each reuse resets the 24-hour clock, to a maximum of 31 days.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d5-007",
    "examId": "snowpro-c03",
    "domainId": "d5",
    "question": "DATA_RETENTION_TIME_IN_DAYS set to 0 on a table means…",
    "options": [
      "Fail-safe is disabled",
      "Time Travel is disabled for that table",
      "The table is transient",
      "Clones are blocked"
    ],
    "correctIndex": 1,
    "explanation": "Retention 0 turns off Time Travel; Fail-safe (permanent tables) still applies.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d5-008",
    "examId": "snowpro-c03",
    "domainId": "d5",
    "question": "UNDROP can restore…",
    "options": [
      "Only tables",
      "Tables, schemas, and databases within Time Travel",
      "Warehouses",
      "Shares"
    ],
    "correctIndex": 1,
    "explanation": "All three object levels, provided retention has not lapsed.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d5-009",
    "examId": "snowpro-c03",
    "domainId": "d5",
    "question": "Which objects are NOT copied by a database clone?",
    "options": [
      "Views",
      "External tables and internal named stages",
      "Schemas",
      "Sequences"
    ],
    "correctIndex": 1,
    "explanation": "Clones skip external tables and internal named stages — a subtle exam favorite.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d5-010",
    "examId": "snowpro-c03",
    "domainId": "d5",
    "question": "A share contains…",
    "options": [
      "Copied data",
      "Grants on a database and selected objects — no data movement",
      "A replica",
      "Files"
    ],
    "correctIndex": 1,
    "explanation": "Sharing is metadata: consumers query the provider’s storage directly.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d5-011",
    "examId": "snowpro-c03",
    "domainId": "d5",
    "question": "Consumers of a direct share can…",
    "options": [
      "Modify shared tables",
      "Only read — no DML, no Time Travel on shared data, no re-sharing",
      "Clone shared tables freely",
      "Add their own data to it"
    ],
    "correctIndex": 1,
    "explanation": "Shared data is strictly read-only and cannot be re-shared onward.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d5-012",
    "examId": "snowpro-c03",
    "domainId": "d5",
    "question": "In a direct share, compute costs are paid by…",
    "options": [
      "The provider",
      "The consumer running the queries",
      "Snowflake",
      "Split 50/50"
    ],
    "correctIndex": 1,
    "explanation": "Provider pays storage; consumers pay their own compute. Reader accounts flip compute to the provider.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d5-013",
    "examId": "snowpro-c03",
    "domainId": "d5",
    "question": "Time Travel queries use AT or BEFORE with which reference points?",
    "options": [
      "Only timestamps",
      "TIMESTAMP, OFFSET (seconds), or STATEMENT (query ID)",
      "Row IDs",
      "Snapshots you create"
    ],
    "correctIndex": 1,
    "explanation": "Three ways to pin a point in time — STATEMENT targets the moment before a specific query.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d5-014",
    "examId": "snowpro-c03",
    "domainId": "d5",
    "question": "CREATE TABLE … CLONE … AT(…) lets you…",
    "options": [
      "Clone into another region",
      "Clone the table as it existed at a past point within Time Travel",
      "Skip grants",
      "Merge clones"
    ],
    "correctIndex": 1,
    "explanation": "Cloning composes with Time Travel for point-in-time recovery copies.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d5-015",
    "examId": "snowpro-c03",
    "domainId": "d5",
    "question": "Replication can cross…",
    "options": [
      "Regions only",
      "Clouds only",
      "Both regions and clouds",
      "Neither"
    ],
    "correctIndex": 2,
    "explanation": "Databases and account objects replicate across region and cloud boundaries.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d5-016",
    "examId": "snowpro-c03",
    "domainId": "d5",
    "question": "Failover groups require which edition?",
    "options": [
      "Standard",
      "Enterprise",
      "Business Critical",
      "Any"
    ],
    "correctIndex": 2,
    "explanation": "Replication is broadly available; orchestrated failover/failback is Business Critical.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d5-017",
    "examId": "snowpro-c03",
    "domainId": "d5",
    "question": "Fail-safe begins…",
    "options": [
      "At table creation",
      "Immediately after the Time Travel retention period ends",
      "After UNDROP",
      "On demand"
    ],
    "correctIndex": 1,
    "explanation": "7 days of last-resort, support-only recovery following Time Travel.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  },
  {
    "id": "snowpro-c03-q-d5-018",
    "examId": "snowpro-c03",
    "domainId": "d5",
    "question": "Paid Marketplace listings let providers…",
    "options": [
      "Sell compute",
      "Monetize data products with usage-based or subscription pricing",
      "Sell warehouses",
      "Avoid contracts"
    ],
    "correctIndex": 1,
    "explanation": "Listings package data/apps with terms, trials, and billing through Snowflake.",
    "distractorRationale": false,
    "official": false,
    "sourceIds": [
      "sp-src-guide-repo",
      "sp-exam-guide",
      "sp-docs"
    ]
  }
];
