/**
 * One-time migration generator: extracts the content corpora from the three
 * source repos + the hand-delivered card file and emits the checked-in
 * content/*.ts files. Committed for provenance — the Phase 1 fidelity gate
 * can re-run it and diff.
 *
 * Usage:
 *   node scripts/migration/gen-content.mjs --sources <dir>
 * where <dir> contains clones of:
 *   exam-prep-app/            (jmiknuk7/exam-prep-app)
 *   snowpro-c03-guide/        (jmiknuk7/snowpro-c03-guide)
 *   cca-gh/                   (avidevelops/claude-architect-exam-prep)
 *   cca-handed-cards.json     (transcribed from CCA_TikTok_Flashcards.jsx)
 *
 * Every editorial decision applied here is recorded in MIGRATION_NOTES.md:
 *   - 9 exam-prep-app questions superseded by avidevelops equivalents
 *   - deletion of one uncited statistic (Amendment 3)
 *   - unverifiedClaims badges
 *   - Q29 migrated as scenario card only (no answer options in source)
 *   - mechanical trap-card front/back split for SnowPro traps
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { createHash } from "node:crypto";
import path from "node:path";
import vm from "node:vm";

const args = process.argv.slice(2);
const srcIdx = args.indexOf("--sources");
if (srcIdx === -1 || !args[srcIdx + 1]) {
  console.error("Usage: node gen-content.mjs --sources <dir-with-clones>");
  process.exit(1);
}
const SRC = args[srcIdx + 1];
const OUT = path.join(import.meta.dirname, "..", "..", "content", "exams");

const report = [];
const log = (s) => { report.push(s); console.log(s); };

/* ---------------- helpers ---------------- */

function grab(src, marker, closer) {
  const start = src.indexOf(marker);
  if (start === -1) throw new Error(`marker not found: ${marker}`);
  const exprStart = start + marker.length;
  const end = src.indexOf(closer, exprStart);
  if (end === -1) throw new Error(`closer not found after: ${marker}`);
  // Re-append the closing bracket (closer is "\n];"-shaped, possibly indented).
  const bracket = closer.trim().slice(0, 1);
  const expr = src.slice(exprStart, end) + "\n" + bracket;
  return vm.runInNewContext("(" + expr + ")", {}, { timeout: 5000 });
}

const ENT = { "&amp;": "&", "&lt;": "<", "&gt;": ">", "&quot;": '"', "&#39;": "'", "&nbsp;": " " };
const decode = (s) => s.replace(/&(amp|lt|gt|quot|#39|nbsp);/g, (m) => ENT[m]);
const stripTags = (s) =>
  decode(s.replace(/<\/span>/g, "</span> ").replace(/<[^>]+>/g, "")).replace(/\s+/g, " ").trim();
const lf = (s) => s.replace(/\r\n/g, "\n");

function tableToMd(html) {
  const rows = [...html.matchAll(/<tr>([\s\S]*?)<\/tr>/g)].map((r) =>
    [...r[1].matchAll(/<t[hd][^>]*>([\s\S]*?)<\/t[hd]>/g)].map((c) => stripTags(c[1])),
  );
  if (!rows.length) return "";
  const md = [];
  md.push("| " + rows[0].join(" | ") + " |");
  md.push("|" + rows[0].map(() => " --- ").join("|") + "|");
  for (const r of rows.slice(1)) md.push("| " + r.join(" | ") + " |");
  return md.join("\n");
}

const preToMd = (html) => "```sql\n" + decode(html.replace(/<[^>]+>/g, "")).trim() + "\n```";

const pad = (n) => String(n).padStart(3, "0");

function writeTs(file, typeName, exportName, data, provenance) {
  const header =
    `// GENERATED by scripts/migration/gen-content.mjs — ${new Date().toISOString().slice(0, 10)}\n` +
    `// Source: ${provenance}\n` +
    `// Do not hand-edit content items: regenerate, or record any manual edit in MIGRATION_NOTES.md.\n` +
    `import type { ${typeName} } from "../../schema";\n\n` +
    `export const ${exportName}: ${typeName}[] = `;
  writeFileSync(file, header + JSON.stringify(data, null, 2) + ";\n", "utf8");
  log(`wrote ${path.relative(process.cwd(), file)} (${data.length} items)`);
}

/* ================= CCA-F ================= */

const appJsx = readFileSync(path.join(SRC, "exam-prep-app", "src", "App.jsx"), "utf8");
const SECTIONS = grab(appJsx, "const SECTIONS = ", "\n};");
const FLASHCARDS = grab(appJsx, "const FLASHCARDS = ", "\n};");
const QUIZ = grab(appJsx, "const QUIZ = ", "\n];");

const CCA_SOURCES_DERIVED = ["ccaf-exam-guide", "ccaf-src-exam-prep-app"];

/* --- sections (49) --- */
const STAT_DELETION = " — 85% of CI integrations use this";
const BARE_CLAIM =
  "\"--bare skips OAuth and keychain reads ... will become the default for -p\" — product behavior claim, checkable against Claude Code docs; not yet verified.";
let statDeleted = false;
const ccaSections = [];
for (const [dom, secs] of Object.entries(SECTIONS)) {
  secs.forEach((s, i) => {
    let body = s.body;
    const unverifiedClaims = [];
    if (body.includes(STAT_DELETION)) {
      body = body.replace(STAT_DELETION, "");
      statDeleted = true;
      log(`Amendment 3: deleted uncited statistic from section ${s.id} ("85% of CI integrations")`);
    }
    if (body.includes("--bare")) unverifiedClaims.push(BARE_CLAIM);
    ccaSections.push({
      id: `cca-f-sec-${dom}-${pad(i + 1)}`,
      examId: "cca-f",
      domainId: dom,
      title: s.title,
      body,
      sourceIds: CCA_SOURCES_DERIVED,
      ...(unverifiedClaims.length ? { unverifiedClaims } : {}),
    });
  });
}
if (!statDeleted) throw new Error("Amendment 3 deletion target not found — source drift?");

/* --- cards: 83 recall (exam-prep-app) + 23 scenario + 13 trap (handed file) --- */
const ccaCards = [];
for (const [dom, cards] of Object.entries(FLASHCARDS)) {
  cards.forEach((c, i) => {
    ccaCards.push({
      id: `cca-f-recall-${dom}-${pad(i + 1)}`,
      examId: "cca-f",
      domainId: dom,
      type: "recall",
      front: c.q,
      back: c.a,
      sourceIds: CCA_SOURCES_DERIVED,
    });
  });
}

const handed = JSON.parse(readFileSync(path.join(SRC, "cca-handed-cards.json"), "utf8"));
const perDomSeq = {};
for (const s of handed.scenario) {
  perDomSeq[s.d] = (perDomSeq[s.d] ?? 0) + 1;
  ccaCards.push({
    id: `cca-f-scen-${s.d}-${pad(perDomSeq[s.d])}`,
    examId: "cca-f",
    domainId: s.d,
    type: "scenario",
    front: s.fr,
    back: s.ba,
    sourceIds: s.tag && s.tag.startsWith("GitHub")
      ? ["ccaf-src-handed-cards", "ccaf-src-avidevelops", "ccaf-exam-guide"]
      : ["ccaf-src-handed-cards", "ccaf-exam-guide"],
    ...(s.tag ? { tag: s.tag } : {}),
  });
}
// Trap domain assignment (editorial, recorded in MIGRATION_NOTES):
const CCA_TRAP_DOMAIN = { tp1: "d1", tp2: "d5", tp3: "d4", tp4: "d4", tp5: "d5", tp6: "d3", tp7: "d1", tp8: "d5", tp9: "d5", tp10: "d5", tp11: "d2", tp12: "d2", tp13: "d1" };
handed.trap.forEach((t, i) => {
  ccaCards.push({
    id: `cca-f-trap-${pad(i + 1)}`,
    examId: "cca-f",
    domainId: CCA_TRAP_DOMAIN[t.id],
    type: "trap",
    front: t.fr,
    back: t.ba,
    sourceIds: ["ccaf-src-handed-cards", "ccaf-exam-guide"],
    tag: t.id,
  });
});

/* --- questions: 96 existing (minus 9 superseded) + 32 avidevelops --- */
const SUPERSEDED = [
  ["Q1", "Invoice extraction sometimes produces totals that do not match line items"],
  ["Q18", "Since then your team merged a PR that refactored the auth module"],
  ["Q19", "Which MCP primitive fits exposing a catalog of database schemas"],
  ["Q22", "source attribution is frequently lost during the handoff"],
  ["Q23", "system prompt is a 40-step procedural checklist"],
  ["Q24", "For parallel subagent execution in the Claude Agent SDK"],
  ["Q25", "government report says 40% growth"],
  ["Q30", "Leadership wants to automate 100% of processing"],
  ["Q33", "You need the model to always call one specific tool for the first action"],
];

const domSeq = {};
const existingQuestions = QUIZ.map((q) => {
  domSeq[q.d] = (domSeq[q.d] ?? 0) + 1;
  return { src: q, id: `cca-f-q-${q.d}-${pad(domSeq[q.d])}` };
});

const supersededIds = [];
for (const [avQ, needle] of SUPERSEDED) {
  const hits = existingQuestions.filter((e) => e.src.q.includes(needle));
  if (hits.length !== 1) throw new Error(`supersession needle for ${avQ} matched ${hits.length} questions: "${needle}"`);
  if (hits[0].src.official) throw new Error(`refusing to supersede an OFFICIAL question with ${avQ}`);
  hits[0].superseded = avQ;
  supersededIds.push(`${hits[0].id} ← superseded by avidevelops ${avQ}`);
}
log(`Superseded ${supersededIds.length} exam-prep-app questions:\n  ` + supersededIds.join("\n  "));

const ccaQuestions = existingQuestions
  .filter((e) => !e.superseded)
  .map((e) => ({
    id: e.id,
    examId: "cca-f",
    domainId: e.src.d,
    question: e.src.q,
    options: e.src.opts,
    correctIndex: e.src.correct,
    explanation: e.src.exp,
    distractorRationale: !!e.src.official, // conservative: only official 12 verified to explain every wrong answer
    official: !!e.src.official,
    ...(e.src.sc ? { scenario: e.src.sc } : {}),
    sourceIds: e.src.official ? ["ccaf-exam-guide"] : CCA_SOURCES_DERIVED,
  }));

/* avidevelops README + contrib JSON */
const readme = readFileSync(path.join(SRC, "cca-gh", "README.md"), "utf8");
const contrib = JSON.parse(
  readFileSync(path.join(SRC, "cca-gh", "contrib", "expanded-counter-explanations.json"), "utf8"),
);
const contribByQ = Object.fromEntries(contrib.questions.map((q) => [q.question_id, q]));

const AV_DOMAIN = { 1: "d4", 2: "d4", 3: "d4", 4: "d5", 5: "d2", 6: "d4", 7: "d2", 8: "d2", 9: "d2", 10: "d2", 11: "d2", 12: "d2", 13: "d2", 14: "d2", 15: "d2", 16: "d2", 17: "d2", 18: "d3", 19: "d2", 20: "d3", 21: "d1", 22: "d1", 23: "d1", 24: "d1", 25: "d5", 26: "d5", 27: "d5", 28: "d5", 29: "d5", 30: "d5", 31: "d5", 32: "d5", 33: "d4" };

const qBlocks = readme.split(/^### Q(\d+): (.+)$/m);
let avCount = 0;
for (let i = 1; i < qBlocks.length; i += 3) {
  const n = Number(qBlocks[i]);
  const block = qBlocks[i + 2];
  const scenario = block.match(/> \*Scenario: (.+?)\*/)?.[1]?.trim();
  const qm = block.match(/\*\*Question:\*\*\s*\n([\s\S]*?)\n\s*\n\*\*(Options|✅)/);
  if (!qm) throw new Error(`Q${n}: question text not found`);
  const question = qm[1].trim();
  const options = [...block.matchAll(/^- ([A-D])\) (.*?)\s*$/gm)].map((m) => m[2].trim());
  const correctLetter = block.match(/\*\*✅ Correct Answer: ([A-D])/)?.[1];
  if (n === 29) {
    if (options.length) throw new Error("Q29 unexpectedly has options now — revisit exclusion");
    log("Q29 has no answer options in source — migrated as scenario card only (cca-f-scen-d5-003), not as MC");
    continue;
  }
  if (options.length !== 4 && options.length !== 5) throw new Error(`Q${n}: ${options.length} options`);
  const whyCorrect = block.match(/\*\*Why this is correct:\*\*\s*\n([\s\S]*?)\n\s*\n\*\*/)?.[1]?.trim();
  const realWorld = block.match(/\*\*⚠️ Real-World Note:\*\*\s*\n([\s\S]*?)\n\s*\n\*\*/)?.[1]?.trim();
  const takeaway = block.match(/\*\*💡 Exam Takeaway:\*\*\s*\n([\s\S]*?)(\n---|\n*$)/)?.[1]?.trim();
  const c = contribByQ[`Q${n}`];
  if (!c) throw new Error(`Q${n}: missing from contrib JSON`);
  let contribUsable = true;
  if (c.correct_option !== correctLetter) {
    // Known case: Q3's answer was corrected to A in the README (commit 579684e)
    // AFTER the contrib enrichment was generated (2026-06-18). The README is
    // the corrected authority; fall back to its own "weaker" bullets.
    contribUsable = false;
    log(`contrib disagreement Q${n}: contrib says ${c.correct_option}, README (corrected) says ${correctLetter} — using README's weaker-bullets for per-option rationale`);
  }
  const contribDomain = c.domain?.toLowerCase();
  if (contribDomain && contribDomain !== AV_DOMAIN[n])
    log(`domain note Q${n}: contrib says ${c.domain}, Rapids assigns ${AV_DOMAIN[n]} (official-guide domain semantics; see MIGRATION_NOTES)`);
  const letters = ["A", "B", "C", "D", "E"];
  const perOption = {};
  if (contribUsable) {
    for (const [letter, text] of Object.entries(c.per_option_counter_explanations ?? {})) {
      perOption[String(letters.indexOf(letter))] = text;
    }
  } else {
    const weaker = block.match(/\*\*Why the others are weaker:\*\*\s*\n([\s\S]*?)\n\s*\n\*\*/)?.[1] ?? "";
    for (const b of [...weaker.matchAll(/^- \*\*([A-D])\)\*\*\s*(.*?)\s*$/gm)]) {
      perOption[String(letters.indexOf(b[1]))] = b[2];
    }
    if (!Object.keys(perOption).length) throw new Error(`Q${n}: no per-option rationale recoverable from README`);
  }
  avCount++;
  ccaQuestions.push({
    id: `cca-f-q-av-q${String(n).padStart(2, "0")}`,
    examId: "cca-f",
    domainId: AV_DOMAIN[n],
    question: lf(question),
    options: options.map(lf),
    correctIndex: letters.indexOf(correctLetter),
    explanation: lf(whyCorrect + (realWorld ? `\n\n⚠️ Real-world note: ${realWorld}` : "")),
    perOptionExplanations: Object.fromEntries(Object.entries(perOption).map(([k, v]) => [k, lf(v)])),
    ...(takeaway ? { examTakeaway: lf(takeaway.replace(/\s*---\s*$/, "")) } : {}),
    distractorRationale: true,
    official: false,
    ...(scenario ? { scenario } : {}),
    sourceIds: ["ccaf-src-avidevelops", "ccaf-exam-guide"],
  });
}
log(`avidevelops questions migrated as MC: ${avCount} (Q29 excluded, card-only)`);

/* official byte-integrity hashes */
const officialHashes = ccaQuestions
  .filter((q) => q.official)
  .map((q) => ({ id: q.id, sha256: createHash("sha256").update(q.question, "utf8").digest("hex") }));

/* ================= SnowPro ================= */

const html = readFileSync(path.join(SRC, "snowpro-c03-guide", "index.html"), "utf8");
const MC = grab(html, "var MC = ", "\n  ];");
const RECALL = grab(html, "var RECALL = ", "\n  ];");
const MC_EXTRA = grab(html, "var MC_EXTRA = ", "\n  ];");
const RECALL_EXTRA = grab(html, "var RECALL_EXTRA = ", "\n  ];");

const SP_SOURCES = ["sp-src-guide-repo", "sp-exam-guide", "sp-docs"];

const spDomSeq = {};
const spQuestions = [...MC, ...MC_EXTRA].map(([d, q, opts, correct, exp]) => {
  spDomSeq[d] = (spDomSeq[d] ?? 0) + 1;
  return {
    id: `snowpro-c03-q-${d}-${pad(spDomSeq[d])}`,
    examId: "snowpro-c03",
    domainId: d,
    question: q,
    options: opts,
    correctIndex: correct,
    explanation: exp,
    distractorRationale: false, // explanations justify the correct answer only → /gaps queue (Amendment 4)
    official: false,
    sourceIds: SP_SOURCES,
  };
});

const spRecallSeq = {};
const spCards = [...RECALL, ...RECALL_EXTRA].map(([d, q, a]) => {
  spRecallSeq[d] = (spRecallSeq[d] ?? 0) + 1;
  return {
    id: `snowpro-c03-recall-${d}-${pad(spRecallSeq[d])}`,
    examId: "snowpro-c03",
    domainId: d,
    type: "recall",
    front: q,
    back: a,
    sourceIds: SP_SOURCES,
  };
});

/* traps: 7 inline (document order) + 10 "why candidates fail" */
const trapMatches = [...html.matchAll(/<div class="trap"><b>([\s\S]*?)<\/b>([\s\S]*?)<\/div>/g)];
if (trapMatches.length !== 17) throw new Error(`expected 17 traps, found ${trapMatches.length}`);
const SP_TRAP_DOMAIN = ["d1", "d1", "d2", "d3", "d4", "d5", "d5", "d1", null, "d4", "d2", "d5", "d3", "d1", null, "d3", null];
trapMatches.forEach((m, i) => {
  const label = stripTags(m[1]);
  const body = stripTags(m[2]);
  const numbered = /^\d+\.$/.test(label);
  const firstSentence = body.split(/(?<=\.)\s/)[0];
  // Mechanical front/back split (no authored content): front = label + first sentence; back = full text.
  spCards.push({
    id: `snowpro-c03-trap-${pad(i + 1)}`,
    examId: "snowpro-c03",
    domainId: SP_TRAP_DOMAIN[i],
    type: "trap",
    front: numbered ? `⚠️ Why candidates fail #${label.replace(".", "")}: ${firstSentence}` : `⚠️ ${label} ${firstSentence}`,
    back: body,
    sourceIds: SP_SOURCES,
  });
});

/* sections: 5 domains + method + plan + examday */
function sectionInner(id) {
  const m = html.match(new RegExp(`<section class="(?:domain|panel)" id="${id}">([\\s\\S]*?)</section>`));
  if (!m) throw new Error(`section ${id} not found`);
  return m[1];
}

function domainSectionToMd(inner) {
  const md = [];
  const checklist = [];
  const blockRe = /<h3>([\s\S]*?)<\/h3>|<div class="tbl-scroll">([\s\S]*?<\/table>)<\/div>|<pre>([\s\S]*?)<\/pre>|<div class="trap">([\s\S]*?)<\/div>|<ul class="check"[^>]*>([\s\S]*?)<\/ul>|<p[^>]*>([\s\S]*?)<\/p>/g;
  let m;
  while ((m = blockRe.exec(inner))) {
    if (m[1] !== undefined) md.push(`### ${stripTags(m[1])}`);
    else if (m[2] !== undefined) md.push(tableToMd(m[2]));
    else if (m[3] !== undefined) md.push(preToMd(m[3]));
    else if (m[4] !== undefined) md.push(`> **${stripTags(m[4]).startsWith("Trap:") ? "" : ""}${stripTags(m[4])}**`);
    else if (m[5] !== undefined)
      for (const l of [...m[5].matchAll(/<label[^>]*>([\s\S]*?)<\/label>/g)]) checklist.push(stripTags(l[1]));
    else if (m[6] !== undefined) {
      const t = stripTags(m[6]);
      if (t) md.push(t);
    }
  }
  return { body: md.join("\n\n"), checklist };
}

const SP_DOMAIN_TITLES = {
  d1: "Snowflake AI Data Cloud Features & Architecture",
  d2: "Account Management & Data Governance",
  d3: "Data Loading, Unloading & Connectivity",
  d4: "Performance Optimization, Querying & Transformation",
  d5: "Data Collaboration",
};
const spSections = [];
for (const d of ["d1", "d2", "d3", "d4", "d5"]) {
  const { body, checklist } = domainSectionToMd(sectionInner(d));
  spSections.push({
    id: `snowpro-c03-sec-${d}`,
    examId: "snowpro-c03",
    domainId: d,
    title: SP_DOMAIN_TITLES[d],
    body,
    checklist,
    sourceIds: SP_SOURCES,
  });
}

/* method panel */
{
  const inner = sectionInner("method");
  const md = [];
  const note = inner.match(/<p class="note">([\s\S]*?)<\/p>/);
  if (note) md.push(stripTags(note[1]));
  for (const meth of [...inner.matchAll(/<div class="method">([\s\S]*?)<\/div>/g)]) {
    const rank = stripTags(meth[1].match(/<span class="rank">([\s\S]*?)<\/span>/)?.[1] ?? "");
    const h4 = stripTags(meth[1].match(/<h4>([\s\S]*?)<\/h4>/)?.[1] ?? "");
    const p = stripTags(meth[1].match(/<p>([\s\S]*?)<\/p>/)?.[1] ?? "");
    const cite = stripTags(meth[1].match(/<cite>([\s\S]*?)<\/cite>/)?.[1] ?? "");
    md.push(`### ${rank} — ${h4}\n\n${p}\n\n*${cite}*`);
  }
  const proto = inner.match(/<div class="protocol">([\s\S]*?)<\/div>/);
  if (proto) md.push(stripTags(proto[1]));
  spSections.push({
    id: "snowpro-c03-sec-method",
    examId: "snowpro-c03",
    domainId: null,
    title: "How to use this guide — what the evidence says",
    body: md.join("\n\n"),
    sourceIds: [...SP_SOURCES, "sp-research-dunlosky2013", "sp-research-roediger2006", "sp-research-cepeda2006", "sp-research-rohrer2007", "sp-research-chi1994"],
  });
}

/* six-week plan */
{
  const inner = sectionInner("plan");
  const md = [];
  const note = inner.match(/<p class="note">([\s\S]*?)<\/p>/);
  if (note) md.push(stripTags(note[1]));
  for (const wk of [...inner.matchAll(/<div class="plan-week">([\s\S]*?)<\/div><\/div>/g)]) {
    const w = stripTags(wk[1].match(/<span class="wk">([\s\S]*?)<\/span>/)?.[1] ?? "");
    const h = stripTags(wk[1].match(/<h4>([\s\S]*?)<\/h4>/)?.[1] ?? "");
    const p = stripTags(wk[1].match(/<p>([\s\S]*?)<\/p>/)?.[1] ?? "");
    md.push(`**${w} — ${h}.** ${p}`);
  }
  spSections.push({
    id: "snowpro-c03-sec-plan",
    examId: "snowpro-c03",
    domainId: null,
    title: "Six-week plan (working professional)",
    body: md.join("\n\n"),
    sourceIds: SP_SOURCES,
  });
}

/* exam-day strategy */
{
  const inner = sectionInner("examday");
  const md = [...inner.matchAll(/<p>([\s\S]*?)<\/p>/g)].map((m) => {
    const t = decode(m[1].replace(/<strong>/g, "**").replace(/<\/strong>/g, "**").replace(/<[^>]+>/g, "")).replace(/\s+/g, " ").trim();
    return t;
  });
  spSections.push({
    id: "snowpro-c03-sec-examday",
    examId: "snowpro-c03",
    domainId: null,
    title: "Exam-day strategy",
    body: md.join("\n\n"),
    sourceIds: SP_SOURCES,
  });
}

/* ================= emit ================= */

mkdirSync(path.join(OUT, "cca-f"), { recursive: true });
mkdirSync(path.join(OUT, "snowpro-c03"), { recursive: true });

writeTs(path.join(OUT, "cca-f", "sections.ts"), "Section", "sections", ccaSections, "jmiknuk7/exam-prep-app src/App.jsx SECTIONS (49 items; one uncited statistic deleted per Amendment 3)");
writeTs(path.join(OUT, "cca-f", "cards.ts"), "Card", "cards", ccaCards, "exam-prep-app FLASHCARDS (83 recall) + CCA_TikTok_Flashcards.jsx (23 scenario, 13 trap)");
writeTs(path.join(OUT, "cca-f", "questions.ts"), "Question", "questions", ccaQuestions, "exam-prep-app QUIZ (96 − 9 superseded) + avidevelops/claude-architect-exam-prep (32 MC, CC BY 4.0)");
writeTs(path.join(OUT, "snowpro-c03", "sections.ts"), "Section", "sections", spSections, "jmiknuk7/snowpro-c03-guide index.html (5 domain sections + method + plan + exam-day)");
writeTs(path.join(OUT, "snowpro-c03", "cards.ts"), "Card", "cards", spCards, "snowpro-c03-guide RECALL+RECALL_EXTRA (52 recall) + 17 trap callouts (mechanical front/back split)");
writeTs(path.join(OUT, "snowpro-c03", "questions.ts"), "Question", "questions", spQuestions, "snowpro-c03-guide MC+MC_EXTRA (133 items; explanations justify correct answer only → distractorRationale:false)");

writeFileSync(
  path.join(import.meta.dirname, "..", "..", "tests", "official-hashes.json"),
  JSON.stringify({ _about: "SHA-256 of each official (verbatim exam-guide) CCA-F question text, generated from the source repo at migration time. The test recomputes from content and must match byte-for-byte.", hashes: officialHashes }, null, 2) + "\n",
  "utf8",
);
log(`official-hashes.json written (${officialHashes.length} official questions frozen)`);

/* composition report */
const count = (arr, f) => arr.reduce((m, x) => ((m[f(x)] = (m[f(x)] ?? 0) + 1), m), {});
log("\n=== COMPOSITION ===");
log(`cca-f: sections=${ccaSections.length} cards=${ccaCards.length} ${JSON.stringify(count(ccaCards, (c) => c.type))} questions=${ccaQuestions.length} ${JSON.stringify(count(ccaQuestions, (q) => q.domainId))} official=${ccaQuestions.filter((q) => q.official).length}`);
log(`snowpro-c03: sections=${spSections.length} cards=${spCards.length} ${JSON.stringify(count(spCards, (c) => c.type))} questions=${spQuestions.length} ${JSON.stringify(count(spQuestions, (q) => q.domainId))}`);

writeFileSync(path.join(import.meta.dirname, "migration-report.txt"), report.join("\n") + "\n", "utf8");
