// GENERATED by scripts/migration/gen-content.mjs — 2026-08-18
// Source: exam-prep-app FLASHCARDS (83 recall) + CCA_TikTok_Flashcards.jsx (23 scenario, 13 trap)
// Do not hand-edit content items: regenerate, or record any manual edit in MIGRATION_NOTES.md.
import type { Card } from "../../schema";

export const cards: Card[] = [
  {
    "id": "cca-f-recall-d1-001",
    "examId": "cca-f",
    "domainId": "d1",
    "type": "recall",
    "front": "Four stop_reason values?",
    "back": "end_turn (final), tool_use (execute and continue), max_tokens (truncated), stop_sequence (hit stop string). Only end_turn and tool_use drive agentic loops.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d1-002",
    "examId": "cca-f",
    "domainId": "d1",
    "type": "recall",
    "front": "Only reliable loop termination signal?",
    "back": "stop_reason == \"end_turn\". Never parse text. Max iterations is a safety net, not a primary terminator.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d1-003",
    "examId": "cca-f",
    "domainId": "d1",
    "type": "recall",
    "front": "Why route all multi-agent communication through the coordinator?",
    "back": "Observability, uniform error handling, controlled information flow. No agent-to-agent spaghetti.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d1-004",
    "examId": "cca-f",
    "domainId": "d1",
    "type": "recall",
    "front": "Do subagents inherit coordinator history?",
    "back": "No. Fully isolated context. Required info must be explicitly passed in the subagent prompt.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d1-005",
    "examId": "cca-f",
    "domainId": "d1",
    "type": "recall",
    "front": "Can subagents spawn their own subagents?",
    "back": "No. Subagents cannot spawn subagents in the Agent SDK.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d1-006",
    "examId": "cca-f",
    "domainId": "d1",
    "type": "recall",
    "front": "Which tool name spawns subagents and what config is required?",
    "back": "\"Task\" (newer SDKs emit \"Agent\"). The coordinator's allowedTools MUST include it or delegation fails.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d1-007",
    "examId": "cca-f",
    "domainId": "d1",
    "type": "recall",
    "front": "How do you run subagents in parallel?",
    "back": "Emit multiple Task calls in a SINGLE coordinator response. The SDK runs them concurrently. Partition work to avoid overlap.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d1-008",
    "examId": "cca-f",
    "domainId": "d1",
    "type": "recall",
    "front": "AgentDefinition required fields?",
    "back": "description (selection signal), prompt (system prompt), tools (least privilege), model (\"sonnet\"/\"opus\"/\"haiku\"/\"inherit\"), mcpServers, skills, maxTurns.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d1-009",
    "examId": "cca-f",
    "domainId": "d1",
    "type": "recall",
    "front": "Four enforcement-relevant hook events?",
    "back": "PreToolUse (deny/allow before exec), PostToolUse (modify after exec, cannot undo), PostToolUseFailure, PermissionRequest.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d1-010",
    "examId": "cca-f",
    "domainId": "d1",
    "type": "recall",
    "front": "Hook vs prompt — deterministic vs probabilistic?",
    "back": "Hooks = 100% deterministic. Prompts = probabilistic (>90%, never 100%). Use hooks for financial/legal/safety rules.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d1-011",
    "examId": "cca-f",
    "domainId": "d1",
    "type": "recall",
    "front": "Can a PreToolUse hook block even in bypassPermissions mode?",
    "back": "Yes. PreToolUse fires BEFORE permission checks. permissionDecision:\"deny\" blocks regardless of permission mode.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d1-012",
    "examId": "cca-f",
    "domainId": "d1",
    "type": "recall",
    "front": "Can PostToolUse hooks undo actions?",
    "back": "No. The tool has already executed. Use PreToolUse for enforcement.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d1-013",
    "examId": "cca-f",
    "domainId": "d1",
    "type": "recall",
    "front": "When to use fork_session?",
    "back": "Exploring divergent approaches from a shared analysis baseline (e.g., compare Redux vs Context API refactor from same codebase exploration).",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d1-014",
    "examId": "cca-f",
    "domainId": "d1",
    "type": "recall",
    "front": "When is a fresh session better than --resume?",
    "back": "When prior tool results are stale (files changed), context has degraded, or you can provide a compact summary instead.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d1-015",
    "examId": "cca-f",
    "domainId": "d1",
    "type": "recall",
    "front": "Prompt chaining vs dynamic decomposition?",
    "back": "Chaining = fixed sequential steps, predictable (code reviews). Dynamic = subtasks generated from intermediate findings, open-ended (legacy codebase investigation).",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d1-016",
    "examId": "cca-f",
    "domainId": "d1",
    "type": "recall",
    "front": "Most common task-decomposition bug?",
    "back": "Over-narrow decomposition. Coordinator misses entire subtopics (e.g., \"creative industries\" → only visual arts, missing music/literature/film).",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d1-017",
    "examId": "cca-f",
    "domainId": "d1",
    "type": "recall",
    "front": "Structured handoff to a human must include?",
    "back": "Customer ID, issue summary, root cause, order IDs, actions_taken, amounts, recommended_action, escalation_reason. Human has NO access to transcript.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d2-001",
    "examId": "cca-f",
    "domainId": "d2",
    "type": "recall",
    "front": "Three MCP primitives?",
    "back": "Tools (executable), Resources (data to read — content catalogs), Prompts (reusable templates invoked as /mcp__server__name).",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d2-002",
    "examId": "cca-f",
    "domainId": "d2",
    "type": "recall",
    "front": "Three MCP transports — which is deprecated?",
    "back": "stdio (local), HTTP (recommended remote), SSE (DEPRECATED — migrate to HTTP). stdio servers must not log to stdout.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d2-003",
    "examId": "cca-f",
    "domainId": "d2",
    "type": "recall",
    "front": "Project-shared MCP config location?",
    "back": ".mcp.json at repo root, committed to git. Use ${ENV_VAR} for secrets. Claude Code prompts for approval on first use.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d2-004",
    "examId": "cca-f",
    "domainId": "d2",
    "type": "recall",
    "front": "Personal MCP config location?",
    "back": "~/.claude.json — user-level, cross-project, not shared.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d2-005",
    "examId": "cca-f",
    "domainId": "d2",
    "type": "recall",
    "front": "Primary mechanism for tool selection?",
    "back": "Tool descriptions. Not the name, not the system prompt. Minimal descriptions cause misrouting among similar tools.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d2-006",
    "examId": "cca-f",
    "domainId": "d2",
    "type": "recall",
    "front": "What should a good tool description include?",
    "back": "What it does/returns, input formats with examples, edge cases, explicit boundaries vs similar tools. Write for the MODEL.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d2-007",
    "examId": "cca-f",
    "domainId": "d2",
    "type": "recall",
    "front": "What is reasoning overload?",
    "back": "Too many tools per agent (18 vs 4-5) degrades selection reliability. Fix: distribute tools across specialized subagents.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d2-008",
    "examId": "cca-f",
    "domainId": "d2",
    "type": "recall",
    "front": "Structured MCP error response fields?",
    "back": "isError:true with errorCategory (transient/validation/business/permission), isRetryable boolean, message, attempted_query, partial_results.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d2-009",
    "examId": "cca-f",
    "domainId": "d2",
    "type": "recall",
    "front": "Access failure vs valid empty result?",
    "back": "Access failure (timeout) → retry decision. Empty result (\"0 matches\") → legitimate answer. Don't conflate.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d2-010",
    "examId": "cca-f",
    "domainId": "d2",
    "type": "recall",
    "front": "Three tool_choice modes?",
    "back": "\"auto\" (model decides or returns text), \"any\" (must call some tool), {\"type\":\"tool\",\"name\":\"x\"} (must call tool x).",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d2-011",
    "examId": "cca-f",
    "domainId": "d2",
    "type": "recall",
    "front": "When to use tool_choice:\"any\"?",
    "back": "Guaranteed structured output when multiple extraction schemas exist and document type is unknown.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d2-012",
    "examId": "cca-f",
    "domainId": "d2",
    "type": "recall",
    "front": "When to use tool_choice:forced?",
    "back": "Ensure a specific tool runs first (e.g., extract_metadata before enrichment in subsequent turns).",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d2-013",
    "examId": "cca-f",
    "domainId": "d2",
    "type": "recall",
    "front": "Built-in tool to find files by name pattern?",
    "back": "Glob. Grep searches file CONTENTS.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d2-014",
    "examId": "cca-f",
    "domainId": "d2",
    "type": "recall",
    "front": "Fallback when Edit fails due to non-unique text match?",
    "back": "Read the full file, modify programmatically, Write the updated version.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d2-015",
    "examId": "cca-f",
    "domainId": "d2",
    "type": "recall",
    "front": "MCP Resources vs Tools — when to use Resource?",
    "back": "Resource for READING data (catalogs, schemas, docs). Tool for ACTIONS. Resources reduce exploratory tool calls.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d3-001",
    "examId": "cca-f",
    "domainId": "d3",
    "type": "recall",
    "front": "Three CLAUDE.md hierarchy levels?",
    "back": "User (~/.claude/CLAUDE.md, personal), Project (.claude/CLAUDE.md, shared via VCS), Directory (CLAUDE.md in subdirs, scoped).",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d3-002",
    "examId": "cca-f",
    "domainId": "d3",
    "type": "recall",
    "front": "New hire missing project context — likely cause?",
    "back": "Conventions stored in ~/.claude/CLAUDE.md (user-level, not shared) instead of .claude/CLAUDE.md (project, committed to git).",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d3-003",
    "examId": "cca-f",
    "domainId": "d3",
    "type": "recall",
    "front": "@import syntax rules?",
    "back": "@ immediately before path (no space). Relative or absolute. Relative resolves to the IMPORTING file. Max nesting depth 5.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d3-004",
    "examId": "cca-f",
    "domainId": "d3",
    "type": "recall",
    "front": "Purpose of .claude/rules/ with paths frontmatter?",
    "back": "Each rule loads ONLY when editing files matching its glob pattern. Saves tokens. Perfect for conventions spanning directories.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d3-005",
    "examId": "cca-f",
    "domainId": "d3",
    "type": "recall",
    "front": "Path-specific rules vs directory CLAUDE.md — when each?",
    "back": "Path-rules for conventions spanning many directories (tests). Directory CLAUDE.md for conventions tied to one location.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d3-006",
    "examId": "cca-f",
    "domainId": "d3",
    "type": "recall",
    "front": "Where do team-shared slash commands live?",
    "back": ".claude/commands/ in the project, committed to VCS. Personal commands in ~/.claude/commands/.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d3-007",
    "examId": "cca-f",
    "domainId": "d3",
    "type": "recall",
    "front": "Skill vs slash command?",
    "back": "Skills auto-discovered by Claude (SKILL.md YAML frontmatter decides applicability). Slash commands explicitly invoked by user.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d3-008",
    "examId": "cca-f",
    "domainId": "d3",
    "type": "recall",
    "front": "Three key SKILL.md frontmatter fields?",
    "back": "context: fork (isolated subagent), allowed-tools (security allowlist), argument-hint (prompts for args if missing).",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d3-009",
    "examId": "cca-f",
    "domainId": "d3",
    "type": "recall",
    "front": "When to use plan mode?",
    "back": "Large-scale changes, multiple valid approaches, architectural decisions (microservice restructuring, library migrations touching 45+ files).",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d3-010",
    "examId": "cca-f",
    "domainId": "d3",
    "type": "recall",
    "front": "When to use direct execution?",
    "back": "Single-file well-scoped changes, clear stack trace, adding one validation check.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d3-011",
    "examId": "cca-f",
    "domainId": "d3",
    "type": "recall",
    "front": "What is the Explore subagent for?",
    "back": "Isolating verbose discovery output from the main context; returns only summaries. Prevents context exhaustion in multi-phase tasks.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d3-012",
    "examId": "cca-f",
    "domainId": "d3",
    "type": "recall",
    "front": "Correct non-interactive CI flag?",
    "back": "-p (or --print). Processes prompt, outputs to stdout, exits.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d3-013",
    "examId": "cca-f",
    "domainId": "d3",
    "type": "recall",
    "front": "Three --output-format values?",
    "back": "text (default), json (structured: result, model, usage, cost_usd, session_id), stream-json (NDJSON for real-time).",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d3-014",
    "examId": "cca-f",
    "domainId": "d3",
    "type": "recall",
    "front": "Flags to enforce schema-compliant output in CI?",
    "back": "--output-format json --json-schema <schema>. Pair with --allowedTools and --max-turns for safety.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d3-015",
    "examId": "cca-f",
    "domainId": "d3",
    "type": "recall",
    "front": "Risk of using the same session to review its own code?",
    "back": "Session retains generation reasoning, biased toward its own decisions. Use an INDEPENDENT session for review.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d3-016",
    "examId": "cca-f",
    "domainId": "d3",
    "type": "recall",
    "front": "/compact risk?",
    "back": "Exact numerics, dates, specifics can be lost to vague summaries. Extract critical facts to a persistent block first.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d3-017",
    "examId": "cca-f",
    "domainId": "d3",
    "type": "recall",
    "front": "Purpose of /memory command?",
    "back": "Verify which memory files are loaded and diagnose inconsistent behavior across sessions.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d4-001",
    "examId": "cca-f",
    "domainId": "d4",
    "type": "recall",
    "front": "Why do \"be conservative\" and \"be careful\" fail?",
    "back": "The model cannot calibrate vague caution. Define WHAT to flag (explicit criteria), not HOW CAREFUL to be.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d4-002",
    "examId": "cca-f",
    "domainId": "d4",
    "type": "recall",
    "front": "Ideal few-shot example count?",
    "back": "2–4 covering edge cases and ambiguous scenarios. Diminishing returns past 4, plus token cost.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d4-003",
    "examId": "cca-f",
    "domainId": "d4",
    "type": "recall",
    "front": "Strongest mechanism for guaranteed JSON output?",
    "back": "tool_use with JSON Schema. Prompt-level \"respond in JSON\" can fail on syntax.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d4-004",
    "examId": "cca-f",
    "domainId": "d4",
    "type": "recall",
    "front": "Does tool_use prevent semantic errors?",
    "back": "No — only syntactic validity. Totals can still not reconcile, values can be in wrong fields. Use validators.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d4-005",
    "examId": "cca-f",
    "domainId": "d4",
    "type": "recall",
    "front": "When is a schema field required?",
    "back": "Only when info is ALWAYS present. Required on missing data pushes the model to fabricate.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d4-006",
    "examId": "cca-f",
    "domainId": "d4",
    "type": "recall",
    "front": "Handle possibly-missing fields?",
    "back": "\"type\": [\"string\", \"null\"]. Model returns null instead of hallucinating.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d4-007",
    "examId": "cca-f",
    "domainId": "d4",
    "type": "recall",
    "front": "Why add \"other\" or \"unclear\" to an enum?",
    "back": "Escape hatches for values outside predefined categories. Honest \"unclear\" beats a confident wrong category.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d4-008",
    "examId": "cca-f",
    "domainId": "d4",
    "type": "recall",
    "front": "When retry-with-error WILL help?",
    "back": "Format errors (wrong date format), structural errors (value in wrong field), arithmetic inconsistencies.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d4-009",
    "examId": "cca-f",
    "domainId": "d4",
    "type": "recall",
    "front": "When retry WILL NOT help?",
    "back": "Info absent from source. Return null or escalate; don't waste tokens retrying.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d4-010",
    "examId": "cca-f",
    "domainId": "d4",
    "type": "recall",
    "front": "Retry cap?",
    "back": "2–3 attempts. Unlimited retries waste tokens.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d4-011",
    "examId": "cca-f",
    "domainId": "d4",
    "type": "recall",
    "front": "Message Batches API savings and window?",
    "back": "50% discount, up to 24-hour window, no latency SLA.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d4-012",
    "examId": "cca-f",
    "domainId": "d4",
    "type": "recall",
    "front": "What is NOT supported in Batches?",
    "back": "Multi-turn tool calling in a single request. Batches are fire-and-forget.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d4-013",
    "examId": "cca-f",
    "domainId": "d4",
    "type": "recall",
    "front": "Blocking PR check — sync or batch?",
    "back": "Synchronous. Batches with 24-hour window are unacceptable for blocking workflows.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d4-014",
    "examId": "cca-f",
    "domainId": "d4",
    "type": "recall",
    "front": "custom_id purpose?",
    "back": "Correlate batch request/response pairs. Required to identify and re-submit failed items.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d4-015",
    "examId": "cca-f",
    "domainId": "d4",
    "type": "recall",
    "front": "Why independent session for review?",
    "back": "Generator-session retains reasoning, biased toward its own decisions. Fresh session = unbiased critique.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d4-016",
    "examId": "cca-f",
    "domainId": "d4",
    "type": "recall",
    "front": "Why single-pass review of 14 files is flawed?",
    "back": "Attention dilution — inconsistent depth, contradictory findings, missed obvious bugs. Split: per-file + cross-file integration pass.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d4-017",
    "examId": "cca-f",
    "domainId": "d4",
    "type": "recall",
    "front": "Is prompt caching implementation on the exam?",
    "back": "Knowing it EXISTS is in scope. Implementation details (TTLs, breakpoints, token minimums) are EXPLICITLY OUT OF SCOPE.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d5-001",
    "examId": "cca-f",
    "domainId": "d5",
    "type": "recall",
    "front": "Lost-in-the-middle effect?",
    "back": "Models reliably process start and end of long inputs but may miss middle findings. Place key info at those positions with explicit headings.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d5-002",
    "examId": "cca-f",
    "domainId": "d5",
    "type": "recall",
    "front": "What degrades during progressive summarization?",
    "back": "Numeric values, percentages, dates become vague (\"about\", \"roughly\"). Extract critical facts to a persistent block before summarization.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d5-003",
    "examId": "cca-f",
    "domainId": "d5",
    "type": "recall",
    "front": "How do you trim verbose tool output?",
    "back": "PostToolUse hook — keep only relevant fields. If lookup_order returns 40 fields and 5 matter, drop 35.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d5-004",
    "examId": "cca-f",
    "domainId": "d5",
    "type": "recall",
    "front": "Purpose of scratchpad files?",
    "back": "Persist key findings across context boundaries. Agent reads and updates. Reclaims tokens, survives session boundaries.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d5-005",
    "examId": "cca-f",
    "domainId": "d5",
    "type": "recall",
    "front": "Appropriate escalation triggers?",
    "back": "Explicit \"get me a manager\", policy gap, inability to progress, financial above threshold (via hook), multiple ambiguous customer matches (ask for ID).",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d5-006",
    "examId": "cca-f",
    "domainId": "d5",
    "type": "recall",
    "front": "Unreliable escalation signals?",
    "back": "Sentiment analysis (mood ≠ complexity), self-reported confidence (confidently wrong), auto-classifier (overengineered).",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d5-007",
    "examId": "cca-f",
    "domainId": "d5",
    "type": "recall",
    "front": "Why is 97% aggregate accuracy potentially misleading?",
    "back": "Hides 40% errors on specific doc types or fields. Use stratified random sampling per type and field.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d5-008",
    "examId": "cca-f",
    "domainId": "d5",
    "type": "recall",
    "front": "How to set confidence thresholds?",
    "back": "Empirically from labeled validation data. Recalibrate on any prompt or model change.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d5-009",
    "examId": "cca-f",
    "domainId": "d5",
    "type": "recall",
    "front": "Structured subagent error includes?",
    "back": "failure_type, attempted_query, partial_results, alternative_approaches, coverage_impact. Never generic \"unavailable\".",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d5-010",
    "examId": "cca-f",
    "domainId": "d5",
    "type": "recall",
    "front": "Why distinguish access failure from valid empty result?",
    "back": "Access failure → retry decision. Empty result → valid answer. Coordinator recovery differs.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d5-011",
    "examId": "cca-f",
    "domainId": "d5",
    "type": "recall",
    "front": "Handle two conflicting sources?",
    "back": "Preserve both with full attribution (source, date, methodology). Annotate conflict_detected. Coordinator reconciles — not the analysis agent.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d5-012",
    "examId": "cca-f",
    "domainId": "d5",
    "type": "recall",
    "front": "Why include dates in source citations?",
    "back": "Temporal differences aren't contradictions. Source A 10% in 2023, B 15% in 2024 = trend.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-d5-013",
    "examId": "cca-f",
    "domainId": "d5",
    "type": "recall",
    "front": "Four context-management strategies?",
    "back": "Subagent delegation, scratchpad files, /compact, structured state persistence (manifests for crash recovery).",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-proj-001",
    "examId": "cca-f",
    "domainId": "proj",
    "type": "recall",
    "front": "When create Project vs ad-hoc chat?",
    "back": "Ongoing work with reused materials, consistent requirements, team collaboration. Not for one-off questions.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-proj-002",
    "examId": "cca-f",
    "domainId": "proj",
    "type": "recall",
    "front": "What triggers RAG mode?",
    "back": "Knowledge approaching context limit. Automatic. Capacity expands up to 10x.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-proj-003",
    "examId": "cca-f",
    "domainId": "proj",
    "type": "recall",
    "front": "Three permission levels?",
    "back": "Can view, Can edit, Owner.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-recall-proj-004",
    "examId": "cca-f",
    "domainId": "proj",
    "type": "recall",
    "front": "Why descriptive filenames matter?",
    "back": "Claude uses filenames to route retrieval. Q4-2025-Sales-Report.pdf beats document1.pdf.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-scen-d1-001",
    "examId": "cca-f",
    "domainId": "d1",
    "type": "scenario",
    "front": "SCENARIO: Follow-up summary queries to the coordinator take 40+ seconds. It spawns a synthesis subagent each time, passing 80K tokens. But the coordinator already has these findings in its context. Best fix?",
    "back": "✅ Handle summarization DIRECTLY at the coordinator level.\nThe coordinator already has the findings — spawning a subagent is the anti-pattern.\n\nSubagents start with ZERO knowledge and cannot inherit coordinator context.\nSpawning one and passing 80K tokens = unnecessary latency + wasteful token transfer.\n\n❌ Compress then pass (still spawns unnecessarily)\n❌ Increase subagent context window (bottleneck is spawn + transfer, not limit)\n❌ Cache subagent responses (band-aid, doesn't fix architectural flaw)\n❌ fork_session (for divergent exploration, not latency optimization)\n\n💡 If the coordinator already has the information, use it directly.",
    "sourceIds": [
      "ccaf-src-handed-cards",
      "ccaf-src-avidevelops",
      "ccaf-exam-guide"
    ],
    "tag": "GitHub Q21"
  },
  {
    "id": "cca-f-scen-d1-002",
    "examId": "cca-f",
    "domainId": "d1",
    "type": "scenario",
    "front": "SCENARIO: After web search and document analysis finish, the coordinator spawns a synthesis subagent. How should findings be passed to it?",
    "back": "✅ Pass COMPLETE findings directly embedded in the synthesis subagent's prompt\nusing a STRUCTURED format separating content from metadata:\n\n{ claim, evidence_excerpt, source_url, document_name, publication_date }\n\n❌ Let synthesis call search tools itself (violates scope separation)\n❌ Let synthesis read coordinator's session history (impossible — isolated)\n❌ Pass prose summary only (loses source attribution — can't cite)\n\n💡 Structured format preserves both content AND metadata for downstream attribution.\n💡 Subagents cannot inherit context — explicitly inject everything.",
    "sourceIds": [
      "ccaf-src-handed-cards",
      "ccaf-src-avidevelops",
      "ccaf-exam-guide"
    ],
    "tag": "GitHub Q22"
  },
  {
    "id": "cca-f-scen-d1-003",
    "examId": "cca-f",
    "domainId": "d1",
    "type": "scenario",
    "front": "SCENARIO: The coordinator gives a web search subagent a 40-step procedural checklist. On emerging topics it reports 'insufficient results' instead of trying alternatives. Fix?",
    "back": "✅ Replace procedural instructions with GOAL-ORIENTED prompts:\n→ Specify research goals + quality criteria\n   (e.g., 'minimum 5 distinct claims from credible sources')\n→ Grants the subagent authority to adapt its approach\n\n❌ More steps in the checklist (compounds rigidity — more steps = more to fail)\n❌ Expand query lists (can't hard-code for unknown/emerging patterns)\n❌ Generic single-word queries (degrades research specificity)\n\n💡 Procedural checklist = rigid executor. Goal-oriented = adaptive agent.\n💡 When pre-specified paths fail, goals let the agent find alternatives.",
    "sourceIds": [
      "ccaf-src-handed-cards",
      "ccaf-src-avidevelops",
      "ccaf-exam-guide"
    ],
    "tag": "GitHub Q23"
  },
  {
    "id": "cca-f-scen-d1-004",
    "examId": "cca-f",
    "domainId": "d1",
    "type": "scenario",
    "front": "SCENARIO: Document analysis subagent processes 12 legal citations SEQUENTIALLY — takes 3+ minutes. How do you reduce latency?",
    "back": "✅ Emit ALL 12 Task tool calls in a SINGLE coordinator response turn.\nSDK runs them CONCURRENTLY.\nTotal time = duration of the LONGEST single task (~15–20s vs 3+ min).\n\n❌ Increase context window (doesn't address sequential architecture)\n❌ fork_session (for divergent exploration, not pipeline parallelism)\n❌ Message Batches API (up to 24-hour SLA — catastrophically worse for this)\n\n💡 Sequential processing of independent parallel tasks = classic anti-pattern.\n💡 Multiple Task calls in ONE response = concurrent execution by the SDK.",
    "sourceIds": [
      "ccaf-src-handed-cards",
      "ccaf-src-avidevelops",
      "ccaf-exam-guide"
    ],
    "tag": "GitHub Q24"
  },
  {
    "id": "cca-f-scen-d2-001",
    "examId": "cca-f",
    "domainId": "d2",
    "type": "scenario",
    "front": "SCENARIO: Agent has 50+ connector tools. Frequently selects the wrong one even when explicitly instructed to search first. Most effective architectural fix?",
    "back": "✅ Add a search_connectors tool that DYNAMICALLY SCOPES the toolset.\nAgent calls search_connectors → system injects only 2–3 matched connectors for the next turn.\n\nReduces decision complexity from 50+ choices to 2–3 choices.\n\n❌ Rewrite all 50 descriptions (50+ active tools still cause overload)\n❌ Monolithic API (removes model's ability to distinguish between variants)\n❌ Better error handling (reactive band-aid — scoping prevents the error)\n\n💡 Dynamic scoping: proactive prevention beats reactive correction.\n💡 Decision complexity with 50+ tools overwhelms even perfect descriptions.",
    "sourceIds": [
      "ccaf-src-handed-cards",
      "ccaf-src-avidevelops",
      "ccaf-exam-guide"
    ],
    "tag": "GitHub Q7"
  },
  {
    "id": "cca-f-scen-d2-002",
    "examId": "cca-f",
    "domainId": "d2",
    "type": "scenario",
    "front": "SCENARIO: Agent queries internal databases but users say 'research database' instead of the exact system name 'db_res_01'. How to make this reliable?",
    "back": "✅ Use an ENUM parameter explicitly listing the allowed database system names.\nModel maps user's natural language to exact backend values BEFORE execution.\nConstraint enforced at the schema level — before the tool runs.\n\n❌ Freeform string + fuzzy backend matching (pushes ambiguity downstream, unpredictable)\n❌ Reject invalid names at runtime (wastes a full execution turn)\n❌ Search all databases simultaneously (spikes cost, latency, context bloat)\n\n💡 Enums constrain LLM output to valid values deterministically.\n💡 Model's semantic understanding maps 'research DB' → 'db_res_01' reliably.",
    "sourceIds": [
      "ccaf-src-handed-cards",
      "ccaf-src-avidevelops",
      "ccaf-exam-guide"
    ],
    "tag": "GitHub Q8"
  },
  {
    "id": "cca-f-scen-d2-003",
    "examId": "cca-f",
    "domainId": "d2",
    "type": "scenario",
    "front": "SCENARIO: Multiple shipping carriers return timestamps/statuses in completely different JSON formats. How should you design tool output?",
    "back": "✅ NORMALIZE carrier responses into a single COMMON SCHEMA before returning to agent.\ne.g., { status, estimated_delivery, carrier_name, tracking_id }\nVendor quirks are abstracted in middleware — the agent sees clean, consistent data.\n\n❌ Pass raw JSON + prompt instructions for parsing (brittle; burns attention on format)\n❌ Separate tools per carrier (bloats the toolset unnecessarily)\n❌ Return raw + normalized (adds noise, wastes context on data agent doesn't need)\n\n💡 Agents reason best over consistent, predictable data structures.\n💡 Normalize BEFORE the agent sees it — not after.",
    "sourceIds": [
      "ccaf-src-handed-cards",
      "ccaf-src-avidevelops",
      "ccaf-exam-guide"
    ],
    "tag": "GitHub Q12"
  },
  {
    "id": "cca-f-scen-d2-004",
    "examId": "cca-f",
    "domainId": "d2",
    "type": "scenario",
    "front": "SCENARIO: Agent chains get_property_details() → gets address → passes to get_neighborhood_info(address). 2-step chain adds latency and failure points. Fix?",
    "back": "✅ Modify get_neighborhood_info to accept property_id DIRECTLY and resolve address INTERNALLY.\nInternalizes the predictable mechanical ID-to-string lookup.\nReduces agent turns and removes a brittle inter-step failure point.\n\n❌ Merge into one get_all_property_data (over-consolidates distinct capabilities)\n❌ Improve the prompt (doesn't fix the architectural latency)\n❌ Middle-tier helper tool (adds surface area, preserves the chaining problem)\n\n💡 Internalize predictable dependencies into tool logic — don't make the LLM do them.\n💡 If the chaining is always the same and always required, it belongs inside the tool.",
    "sourceIds": [
      "ccaf-src-handed-cards",
      "ccaf-src-avidevelops",
      "ccaf-exam-guide"
    ],
    "tag": "GitHub Q11"
  },
  {
    "id": "cca-f-scen-d2-005",
    "examId": "cca-f",
    "domainId": "d2",
    "type": "scenario",
    "front": "SCENARIO: update_game_score(date, team_name) frequently fails due to ambiguous nicknames and rematches on the same day. Most reliable architectural fix?",
    "back": "✅ Introduce a search_games tool that returns a game_id.\nUpdate the scoring tool to accept ONLY the game_id.\n\nSeparates DISCOVERY (finding the right game) from ACTION (updating its score).\nMachine-usable IDs = no ambiguity.\n\n❌ Strict ISO-8601 date + official team names (doesn't solve rematches on same day)\n❌ Better tool descriptions (doesn't eliminate inherent NL ambiguity)\n❌ Regex validation (catches format errors but doesn't resolve the correct game)\n\n💡 Replace tools relying on ambiguous human-entered text with a lookup/action pattern.\n💡 Rule: if two items have the same human-readable attributes, use an ID.",
    "sourceIds": [
      "ccaf-src-handed-cards",
      "ccaf-src-avidevelops",
      "ccaf-exam-guide"
    ],
    "tag": "GitHub Q13"
  },
  {
    "id": "cca-f-scen-d2-006",
    "examId": "cca-f",
    "domainId": "d2",
    "type": "scenario",
    "front": "SCENARIO: Agent processes employee reimbursements. Policy: payouts > $500 CANNOT be automatically disbursed — must go to pending approval. Where must this rule be enforced?",
    "back": "✅ INSIDE the process_reimbursement tool logic itself (deterministic enforcement).\nEven if the agent hallucinates or is prompt-injected,\npayloads over $500 will always degrade to 'pending approval'.\n\n❌ requires_approval boolean the agent sets (agent could hallucinate false)\n❌ Strict system prompt instruction (probabilistic — non-zero failure rate)\n❌ Two separate tools + trust agent to pick (agent selection can fail)\n\n💡 If a rule CANNOT be bypassed → backend enforcement, not prompt.\n💡 This is the canonical 'hooks vs prompts' example at the tool level.",
    "sourceIds": [
      "ccaf-src-handed-cards",
      "ccaf-src-avidevelops",
      "ccaf-exam-guide"
    ],
    "tag": "GitHub Q14"
  },
  {
    "id": "cca-f-scen-d2-007",
    "examId": "cca-f",
    "domainId": "d2",
    "type": "scenario",
    "front": "SCENARIO: An MCP server exposes content catalogs, issue hierarchies, and schemas. Agents waste time making sequential lookup calls just to discover what data exists. Fix?",
    "back": "✅ Expose each MCP server's content catalog as an MCP RESOURCE.\nAgents can read what data exists BEFORE deciding which tool calls to make.\nEliminates exploratory 'what's in here?' spam.\n\n❌ Consolidate all MCP servers into one giant endpoint (destroys microservice boundaries)\n❌ Add a discover_data tool to every server (re-invents what Resources already do natively)\n❌ Keyword routing at coordinator (brittle when questions span multiple systems)\n\n💡 MCP Resources = lightweight context. MCP Tools = execution.\n💡 Agents should be able to 'see the map' before 'taking the journey'.",
    "sourceIds": [
      "ccaf-src-handed-cards",
      "ccaf-src-avidevelops",
      "ccaf-exam-guide"
    ],
    "tag": "GitHub Q19"
  },
  {
    "id": "cca-f-scen-d3-001",
    "examId": "cca-f",
    "domainId": "d3",
    "type": "scenario",
    "front": "SCENARIO: New developer joins the team. Claude Code doesn't apply project conventions. Team lead stored all conventions in ~/.claude/CLAUDE.md on their own machine. Fix?",
    "back": "✅ Move conventions to .claude/CLAUDE.md at the PROJECT ROOT, committed to git.\nAutomatically available to everyone who clones the repo — no manual steps.\n\n❌ Have new hire copy the lead's CLAUDE.md (manual, error-prone, doesn't scale)\n❌ Put in README.md (Claude doesn't auto-discover README files)\n❌ Set ANTHROPIC_CLAUDE_PATH env var (this env variable doesn't exist)\n\n💡 ~/.claude/ = user-level = personal = NOT version-controlled\n💡 .claude/ at project root = project-level = team-wide = git-tracked\n\nDiagnose: /memory command shows which files are actually loaded.",
    "sourceIds": [
      "ccaf-src-handed-cards",
      "ccaf-src-avidevelops",
      "ccaf-exam-guide"
    ],
    "tag": "GitHub Q18-style"
  },
  {
    "id": "cca-f-scen-d3-002",
    "examId": "cca-f",
    "domainId": "d3",
    "type": "scenario",
    "front": "SCENARIO: PR review workflow: every PR must be reviewed for code style, security vulnerabilities, AND documentation accuracy. Which architectural pattern?",
    "back": "✅ PROMPT CHAINING: separate sequential passes, each with a distinct focus.\n1. Style pass: only evaluate code formatting and conventions\n2. Security pass: only look for vulnerability patterns\n3. Documentation pass: only verify accuracy of comments and docs\nMerge outputs into final synthesis.\n\n❌ Dynamic subagent decomposition (the workflow is predictable and ALWAYS the same)\n❌ A routing agent (all 3 aspects are needed for EVERY PR, not just one)\n❌ Single massive prompt covering all 3 simultaneously (attention dilution across concerns)\n\n💡 When workflow is highly predictable and mandatory: prompt chaining.\n💡 Isolating distinct cognitive lenses prevents cross-contamination.",
    "sourceIds": [
      "ccaf-src-handed-cards",
      "ccaf-src-avidevelops",
      "ccaf-exam-guide"
    ],
    "tag": "GitHub Q20"
  },
  {
    "id": "cca-f-scen-d3-003",
    "examId": "cca-f",
    "domainId": "d3",
    "type": "scenario",
    "front": "SCENARIO: You're restructuring a monolith into 40+ microservices — changes across dozens of files, decisions about service boundaries and module dependencies. Best approach?",
    "back": "✅ PLAN MODE: Explore codebase, understand dependencies, design approach BEFORE making changes.\n→ Safe exploration + architectural design with zero side effects\n→ User reviews and approves the plan before any changes happen\n→ Then direct execution for the approved implementation\n\n❌ Start with direct execution and make incremental changes\n   (risks costly rework when dependency conflicts discovered late)\n❌ Direct execution with comprehensive upfront instructions\n   (assumes you know the structure without exploring it first)\n\n💡 Large-scale + architectural decisions → plan mode first, always.\n💡 The cost of a planning pass is trivial vs. the cost of reversing wrong changes.",
    "sourceIds": [
      "ccaf-src-handed-cards",
      "ccaf-exam-guide"
    ]
  },
  {
    "id": "cca-f-scen-d4-001",
    "examId": "cca-f",
    "domainId": "d4",
    "type": "scenario",
    "front": "SCENARIO: Invoice extraction: extracted line items don't sum to the stated total. Best architectural approach?",
    "back": "✅ Extract BOTH stated_total AND calculated_total.\nCompare them. Flag mismatches with conflict_detected: true for human review.\n\nJSON schema prevents SYNTAX errors.\nSelf-correction patterns handle SEMANTIC errors (bad math).\n\n❌ Adjust line items to match total (FABRICATES data — corrupts integrity)\n❌ Secondary LLM reconciliation step (unnecessary overhead when deterministic check works)\n❌ More few-shot math examples (cannot guarantee arithmetic deterministically)\n\n💡 Downstream code handles discrepancy explicitly rather than silently 'fixing' source.\n💡 Honest conflict flag > silent incorrect data every time.",
    "sourceIds": [
      "ccaf-src-handed-cards",
      "ccaf-src-avidevelops",
      "ccaf-exam-guide"
    ],
    "tag": "GitHub Q1"
  },
  {
    "id": "cca-f-scen-d4-002",
    "examId": "cca-f",
    "domainId": "d4",
    "type": "scenario",
    "front": "SCENARIO: Processing 50K documents. Initial 500-doc test shows 18% need 2–3 prompt refinements. Most cost-efficient strategy?",
    "back": "✅ Refine prompt on representative SAMPLE to maximize first-pass success.\nTHEN batch-process all 50K documents.\n\nIterative resubmissions at scale destroy Batch API cost savings.\nFix the failure modes on 500 docs — then batch.\n\n❌ Batch all 50K immediately (expensive cycles of large-batch resubmission)\n❌ Sync API for all 50K (loses the 50% cost savings)\n❌ Incremental 5K batches (still pays for failure learning at near-production scale)\n\n💡 Refine → stabilize → batch. Order matters enormously for cost.\n💡 18% failure at 50K = 9,000 resubmissions if not fixed first.",
    "sourceIds": [
      "ccaf-src-handed-cards",
      "ccaf-src-avidevelops",
      "ccaf-exam-guide"
    ],
    "tag": "GitHub Q2"
  },
  {
    "id": "cca-f-scen-d4-003",
    "examId": "cca-f",
    "domainId": "d4",
    "type": "scenario",
    "front": "SCENARIO: SLA requires results within 30 hours. Batch API takes up to 24h. Which submission frequency meets SLA while maximizing cost efficiency?",
    "back": "✅ Every 6 HOURS — the maximum interval that still satisfies the SLA.\n\nMath: batch_interval + 24h ≤ 30h → interval ≤ 6h\n6h = fewest submissions = lowest overhead = maximum cost efficiency.\nIt sits precisely on the optimal boundary.\n\n❌ Every 4h: meets SLA but submits more batches than necessary (extra overhead)\n❌ Once daily: 24 + 24 = 48h → FAILS the 30h SLA\n❌ Sync API: loses 50% cost savings\n\n⚠️ Exam asks for MAX COST EFFICIENCY → 6h is correct (on the boundary)\n⚠️ Production reality: use 4h buffer. Exam: 6h.",
    "sourceIds": [
      "ccaf-src-handed-cards",
      "ccaf-src-avidevelops",
      "ccaf-exam-guide"
    ],
    "tag": "GitHub Q3"
  },
  {
    "id": "cca-f-scen-d4-004",
    "examId": "cca-f",
    "domainId": "d4",
    "type": "scenario",
    "front": "SCENARIO: Pipeline uses extract_metadata (returns DOI) + enrichment tools that REQUIRE a DOI first. Model sometimes calls enrichment first, which fails. Fix?",
    "back": "✅ Set tool_choice: {\"type\":\"tool\",\"name\":\"extract_metadata\"} on TURN 1.\nThen switch to tool_choice: \"auto\" for subsequent turns.\nDOI is now in context → enrichment tools function correctly.\n\n❌ Prompt instruction \"always call extract_metadata first\" (non-zero failure rate)\n❌ Merge all tools into one (decreases composability, massively bloats complexity)\n❌ \"auto\" + restrict enrichment descriptions (model may still call them in same turn)\n\n💡 When deterministic execution order matters → deterministic API constraint.\n💡 Probabilistic prompt guidance never guarantees execution order.",
    "sourceIds": [
      "ccaf-src-handed-cards",
      "ccaf-src-avidevelops",
      "ccaf-exam-guide"
    ],
    "tag": "GitHub Q33"
  },
  {
    "id": "cca-f-scen-d5-001",
    "examId": "cca-f",
    "domainId": "d5",
    "type": "scenario",
    "front": "SCENARIO: Technical manual lists two conflicting battery capacities — body text says one value, specs table says another (historically 90% correct). How should the schema handle this?",
    "back": "✅ Change the field to capture ALL conflicting values WITH their source locations.\nPreserve provenance for downstream reconciliation.\nDon't force premature collapse into a single value.\n\n❌ Halt and flag for manual correction before extraction (impractical at scale)\n❌ Single-value schema + prompt to pick most likely (destroys conflict evidence)\n❌ Hard-code 'always use specs table' (locks in a guaranteed 10% error rate)\n\n💡 Even at 90% reliability, hardcoding guarantees 10% wrong data.\n💡 Preserve conflict structurally — let downstream logic with full context decide.",
    "sourceIds": [
      "ccaf-src-handed-cards",
      "ccaf-src-avidevelops",
      "ccaf-exam-guide"
    ],
    "tag": "GitHub Q4"
  },
  {
    "id": "cca-f-scen-d5-002",
    "examId": "cca-f",
    "domainId": "d5",
    "type": "scenario",
    "front": "SCENARIO: Multi-agent pipeline crashes after completing 12 of 18 documents. How to resume without losing fidelity or repeating completed work?",
    "back": "✅ Extract completed work to a STRUCTURED JSON CHECKPOINT file.\nStart a FRESH session.\nInject checkpoint at top of the prompt:\n• complete: [list of finished docs]\n• partial: [partially processed with sections complete]\n• pending: [not yet started]\n\n❌ --resume directly on crashed session (stale tool results → unreliable reasoning)\n❌ fork_session (for divergent exploration, NOT crash recovery)\n❌ Resume without marking partial states (agent re-does or skips work)\n\n💡 Stale tool results from a crashed session are untrustworthy.\n💡 Checkpoint → fresh session → inject → resume from verified good state.",
    "sourceIds": [
      "ccaf-src-handed-cards",
      "ccaf-src-avidevelops",
      "ccaf-exam-guide"
    ],
    "tag": "GitHub Q28"
  },
  {
    "id": "cca-f-scen-d5-003",
    "examId": "cca-f",
    "domainId": "d5",
    "type": "scenario",
    "front": "SCENARIO: 2024 web search stats vs. 2021 document analysis stats get flagged as 'contradictory' by the synthesis agent. Single best fix?",
    "back": "✅ Require publication_date in structured subagent outputs.\nUpdate synthesis agent instructions:\n→ Differing values across DISTINCT dates = temporal progression, not conflict\n→ conflict_detected: true ONLY for same time period with different values\n\nWith dates: { value: '$35B', date: '2021' } and { value: '$50B', date: '2024' }\n→ Synthesis correctly identifies a GROWTH TREND, not a contradiction\n\n❌ Pick most recent value (misses the temporal analysis entirely)\n❌ Average the values (fabricates a number neither source supports)\n\n💡 Temporal metadata prevents chronological growth from being misread as conflict.",
    "sourceIds": [
      "ccaf-src-handed-cards",
      "ccaf-src-avidevelops",
      "ccaf-exam-guide"
    ],
    "tag": "GitHub Q29"
  },
  {
    "id": "cca-f-scen-d5-004",
    "examId": "cca-f",
    "domainId": "d5",
    "type": "scenario",
    "front": "SCENARIO: 10K batch completes. 300 docs (3%) fail with context_length_exceeded. Most cost-effective fix?",
    "back": "✅ Extract ONLY the 300 failed documents using their custom_id.\nCHUNK them into smaller segments.\nResubmit ONLY the failures as a new batch.\n\n❌ Resubmit all 10K with smaller chunk size\n   (pays for 9,700 already-successful documents — massive waste)\n❌ Switch the 300 to sync API (2x cost; no latency benefit for docs requiring chunking)\n❌ Increase context window limit globally (fixed model constraint — not configurable)\n\n💡 custom_id maps each request to its response. Isolation of failures is trivial.\n💡 Resubmitting only failures = preserving the Batch API cost advantage.",
    "sourceIds": [
      "ccaf-src-handed-cards",
      "ccaf-src-avidevelops",
      "ccaf-exam-guide"
    ],
    "tag": "GitHub Q31"
  },
  {
    "id": "cca-f-scen-d5-005",
    "examId": "cca-f",
    "domainId": "d5",
    "type": "scenario",
    "front": "SCENARIO: Synthesis agent passes prose summary → report agent can't attribute claims because source metadata was lost during summarization. Fix?",
    "back": "✅ Assign citation_id at the EARLIEST source discovery stage.\nRequire synthesis agent to produce:\n  (a) narrative with inline [src_001] references AND\n  (b) separate structured citation index: { id, url, source, date, key_quote }\n\n❌ Re-include full source text in summary (context bloat → lost in middle failures)\n❌ Report agent infers sources from claims (hallucinates plausible-sounding citations)\n❌ Prompt synthesis to 'preserve sources' in prose\n   (probabilistic — drops under token pressure; not structural)\n\n💡 Separate content from metadata STRUCTURALLY.\n💡 Never rely on prose summaries to preserve both simultaneously.",
    "sourceIds": [
      "ccaf-src-handed-cards",
      "ccaf-src-avidevelops",
      "ccaf-exam-guide"
    ],
    "tag": "GitHub Q27"
  },
  {
    "id": "cca-f-trap-001",
    "examId": "cca-f",
    "domainId": "d1",
    "type": "trap",
    "front": "⚠️ TRAP: 'Add few-shot examples to enforce TOOL ORDERING'",
    "back": "❌ WRONG.\n\nTool ordering is a COMPLIANCE concern, not a demonstration concern.\nFew-shot examples influence behavior probabilistically — never deterministically.\n\n✅ CORRECT: Programmatic prerequisites / forced tool_choice\n• Block process_refund until get_customer returns verified customer ID\n• tool_choice: {type:'tool', name:'extract_metadata'} on first turn\n• PreToolUse hook that checks prerequisite state\n\n💡 Compliance-critical ordering = deterministic API constraints.\n💡 Few-shot examples for ordering = hoping the model 'gets it.'\n   With financial consequences on the line, hope is not an architecture.",
    "sourceIds": [
      "ccaf-src-handed-cards",
      "ccaf-exam-guide"
    ],
    "tag": "tp1"
  },
  {
    "id": "cca-f-trap-002",
    "examId": "cca-f",
    "domainId": "d5",
    "type": "trap",
    "front": "⚠️ TRAP: 'Route escalations based on self-reported confidence scores'",
    "back": "❌ WRONG.\n\nLLM self-reported confidence is POORLY CALIBRATED.\nThe model is confidently WRONG on the hard cases that most need routing.\n\nCorrect calibration:\n• Collect model confidence scores on LABELED VALIDATION DATA\n• Measure ACTUAL accuracy vs. reported confidence\n• Set thresholds EMPIRICALLY\n• Recalibrate on every prompt or model change\n\n✅ CORRECT escalation triggers:\n• Customer explicitly requests a human\n• Policy is ambiguous or silent on the specific situation\n• Agent cannot make meaningful progress\n\n💡 Don't ask the model how confident it is. Measure it empirically.",
    "sourceIds": [
      "ccaf-src-handed-cards",
      "ccaf-exam-guide"
    ],
    "tag": "tp2"
  },
  {
    "id": "cca-f-trap-003",
    "examId": "cca-f",
    "domainId": "d4",
    "type": "trap",
    "front": "⚠️ TRAP: 'Switch all workflows to Batch API for 50% cost savings'",
    "back": "❌ WRONG.\n\nBatch API has NO guaranteed SLA — up to 24-hour window.\nThis makes it UNSUITABLE for any BLOCKING workflow.\n\nBlocking workflows that MUST use real-time API:\n• Pre-merge PR checks (developer is waiting)\n• Live customer interactions\n• Any workflow where a human blocks on the result\n\n✅ Batch API for: overnight reports, weekly audits, nightly test gen, bulk non-blocking processing\n\n💡 It's a LATENCY decision, not just a cost decision.\n💡 Cost savings are worthless if developers wait 24 hours for a PR check.",
    "sourceIds": [
      "ccaf-src-handed-cards",
      "ccaf-exam-guide"
    ],
    "tag": "tp3"
  },
  {
    "id": "cca-f-trap-004",
    "examId": "cca-f",
    "domainId": "d4",
    "type": "trap",
    "front": "⚠️ TRAP: 'Use a higher-tier model with a larger context window to fix attention dilution'",
    "back": "❌ WRONG.\n\nContext window SIZE ≠ attention QUALITY.\n\nA 200K context window can still suffer 'lost in the middle.'\nThe model can miss findings from middle sections regardless of window size.\n\n✅ CORRECT approaches:\n• Split into focused per-file passes + cross-file integration pass\n• Place key findings SUMMARY at the BEGINNING of aggregated inputs\n• Use explicit section headers to organize long inputs\n• Spawn subagents for parallel focused analysis\n\n💡 Bigger window = more room. It does NOT fix how attention is distributed.",
    "sourceIds": [
      "ccaf-src-handed-cards",
      "ccaf-exam-guide"
    ],
    "tag": "tp4"
  },
  {
    "id": "cca-f-trap-005",
    "examId": "cca-f",
    "domainId": "d5",
    "type": "trap",
    "front": "⚠️ TRAP: 'Return empty results on subagent failure — graceful degradation'",
    "back": "❌ WRONG. Silent suppression is an anti-pattern.\n\nEmpty result = coordinator CANNOT distinguish between:\n• 'No matches found' (valid, legitimate empty result)\n• 'Agent failed' (error requiring recovery)\n\nThis prevents any recovery and risks incomplete outputs presented as complete.\n\n✅ CORRECT: Return structured error context\n{ failure_type, attempted_query, partial_results, potential_alternatives }\n\n💡 The coordinator needs the distinction to decide:\n   retry? try alternative source? annotate as gap in synthesis?\n💡 What the coordinator cannot see, it cannot recover from.",
    "sourceIds": [
      "ccaf-src-handed-cards",
      "ccaf-exam-guide"
    ],
    "tag": "tp5"
  },
  {
    "id": "cca-f-trap-006",
    "examId": "cca-f",
    "domainId": "d3",
    "type": "trap",
    "front": "⚠️ TRAP: 'Store team coding conventions in ~/.claude/CLAUDE.md'",
    "back": "❌ WRONG.\n\n~/.claude/CLAUDE.md is USER-LEVEL — it lives on the lead's machine only.\nNew team members NEVER receive these conventions.\nThis file is NOT version-controlled, NOT sharable.\n\n✅ CORRECT: .claude/CLAUDE.md at project root, committed to git.\nAutomatically available to everyone who clones the repository.\n\n⚠️ EXAM FAVORITE: 'New developer joins, conventions not applied'\n→ Root cause: conventions stored at user-level instead of project-level\n\nDiagnose with /memory command: shows which files are actually loaded.",
    "sourceIds": [
      "ccaf-src-handed-cards",
      "ccaf-exam-guide"
    ],
    "tag": "tp6"
  },
  {
    "id": "cca-f-trap-007",
    "examId": "cca-f",
    "domainId": "d1",
    "type": "trap",
    "front": "⚠️ TRAP: 'Parse assistant text for \"task complete\" to terminate an agentic loop'",
    "back": "❌ WRONG.\n\nNatural language parsing is UNRELIABLE for loop termination.\nModel might phrase completion differently, or produce this text mid-task.\n\n✅ CORRECT: Check stop_reason\n• stop_reason === 'tool_use' → execute tool, append result, CONTINUE loop\n• stop_reason === 'end_turn' → terminate, return response to user\n\n⚠️ Iteration caps = safety net ONLY (not the primary termination mechanism)\n\n💡 stop_reason is the only reliable, deterministic loop control signal.\n💡 It cannot be mimicked by model output. It IS the API contract.",
    "sourceIds": [
      "ccaf-src-handed-cards",
      "ccaf-exam-guide"
    ],
    "tag": "tp7"
  },
  {
    "id": "cca-f-trap-008",
    "examId": "cca-f",
    "domainId": "d5",
    "type": "trap",
    "front": "⚠️ TRAP: 'Use sentiment analysis to detect when to escalate to a human'",
    "back": "❌ WRONG.\n\nFrustration ≠ case complexity.\n\nA customer can be furious about a simple item replacement — no escalation needed.\nA complex policy exception customer might be perfectly calm — escalation needed.\n\n✅ CORRECT escalation triggers:\n• Customer EXPLICITLY requests a human → immediate escalation\n• Policy gap (ambiguous/silent on specific request)\n• Agent cannot make meaningful progress\n\nFor frustration without explicit escalation request:\n→ Acknowledge → propose concrete resolution\n→ Escalate ONLY if customer REITERATES the human request",
    "sourceIds": [
      "ccaf-src-handed-cards",
      "ccaf-exam-guide"
    ],
    "tag": "tp8"
  },
  {
    "id": "cca-f-trap-009",
    "examId": "cca-f",
    "domainId": "d5",
    "type": "trap",
    "front": "⚠️ TRAP: 'Blindly use --resume to restart a crashed pipeline'",
    "back": "❌ WRONG.\n\n--resume on a crashed session = stale, unreliable tool results.\nAgent may re-process completed docs or skip partially processed ones.\n\n✅ CORRECT:\n1. Extract completed work to structured JSON CHECKPOINT\n   { complete: [...], partial: [{id, sections_done}], pending: [...] }\n2. Start a FRESH session\n3. INJECT checkpoint at top of the prompt\n→ Agent knows exactly where to resume from\n\nfork_session = divergent exploration from shared baseline\n--resume = continue a valid prior session\nCheckpoint + fresh session = crash recovery\n\n💡 Stale tool results are untrustworthy. Always checkpoint before they become needed.",
    "sourceIds": [
      "ccaf-src-handed-cards",
      "ccaf-exam-guide"
    ],
    "tag": "tp9"
  },
  {
    "id": "cca-f-trap-010",
    "examId": "cca-f",
    "domainId": "d5",
    "type": "trap",
    "front": "⚠️ TRAP: 'Prose summaries passed between agents preserve source attribution'",
    "back": "❌ WRONG.\n\nProse summaries COMPRESS metadata:\n• URLs, page numbers, publication dates collapse into sentences\n• Under token pressure, models drop metadata from prose\n• Once lost, attribution cannot be reconstructed downstream\n\n✅ CORRECT structural approach:\n1. Assign citation_id at SOURCE DISCOVERY level\n2. Synthesis writes narrative with inline [src_001] references\n3. Pass SEPARATE structured citation index:\n   { id, url, source_name, date, key_quote }\n\n💡 Separate content from metadata STRUCTURALLY.\n💡 Never rely on prose to preserve both simultaneously.",
    "sourceIds": [
      "ccaf-src-handed-cards",
      "ccaf-exam-guide"
    ],
    "tag": "tp10"
  },
  {
    "id": "cca-f-trap-011",
    "examId": "cca-f",
    "domainId": "d2",
    "type": "trap",
    "front": "⚠️ TRAP: 'tool_choice: \"any\" forces the model to call a specific named tool'",
    "back": "❌ WRONG.\n\n\"any\" means the model MUST call SOME tool — but it CHOOSES WHICH.\n\n✅ Correct distinctions:\n• \"auto\" → model decides: call a tool OR return text (default)\n• \"any\" → model MUST call A tool; picks which one itself\n• {\"type\":\"tool\",\"name\":\"X\"} → model MUST call THIS SPECIFIC NAMED TOOL\n\nWhen to use each:\n• \"auto\" → most cases\n• \"any\" → need guaranteed structured output; model picks the right schema\n• Forced → enforcing prerequisite execution order\n\n💡 \"any\" ≠ forced. \"any\" guarantees a tool call. Forced guarantees WHICH tool.",
    "sourceIds": [
      "ccaf-src-handed-cards",
      "ccaf-exam-guide"
    ],
    "tag": "tp11"
  },
  {
    "id": "cca-f-trap-012",
    "examId": "cca-f",
    "domainId": "d2",
    "type": "trap",
    "front": "⚠️ TRAP: 'Add more detailed system prompt instructions to fix tool selection errors'",
    "back": "❌ WRONG as a first step.\n\nRoot cause: tool DESCRIPTIONS are the primary selection mechanism.\nMinimal/overlapping descriptions = model guesses, not reads instructions.\nAdding system prompt text doesn't fix the root cause.\n\n✅ CORRECT first step: EXPAND AND CLARIFY TOOL DESCRIPTIONS\n→ Include input formats, example queries, edge cases\n→ Define explicit NEGATIVE BOUNDARIES vs similar tools\n   ('archive_file: Do NOT use for compliance files — use archive_for_compliance')\n→ Rename to eliminate functional overlap\n→ Then add system prompt context IF descriptions alone aren't sufficient\n\n💡 Fix descriptions first. Routing classifiers = over-engineering before basics are right.",
    "sourceIds": [
      "ccaf-src-handed-cards",
      "ccaf-exam-guide"
    ],
    "tag": "tp12"
  },
  {
    "id": "cca-f-trap-013",
    "examId": "cca-f",
    "domainId": "d1",
    "type": "trap",
    "front": "⚠️ TRAP: 'Subagents share memory and can access each other's results'",
    "back": "❌ WRONG.\n\nSubagents do NOT share memory between invocations.\nEach Task tool invocation creates a fresh, fully isolated context.\n\nThere is NO:\n• Shared state between subagents\n• Automatic history propagation from coordinator to subagents\n• Memory that persists across Task tool invocations\n\n✅ CORRECT:\n• Pass ALL required information explicitly in each subagent's prompt\n• Coordinator holds state and injects relevant pieces into each subagent's context\n• Use structured state files (scratchpad.md, agent-state/*.json) for persistence\n\n💡 Every subagent starts fresh. Architect for it explicitly — don't work around it.",
    "sourceIds": [
      "ccaf-src-handed-cards",
      "ccaf-exam-guide"
    ],
    "tag": "tp13"
  }
];
