import type { ExamManifest } from "../../schema";

/**
 * All values migrated from jmiknuk7/exam-prep-app (commit 706db1e), which
 * carries them from the official Anthropic CCA-F exam guide (v0.1, Feb 2026).
 * Domain weights are stated by the official guide → weightsVerified: true.
 * Accent colors are provisional until the Phase 5 brand pass (must hold
 * WCAG AA on the dark surface).
 */
export const manifest: ExamManifest = {
  id: "cca-f",
  slug: "claude-certified-architect-foundations",
  name: "Claude Certified Architect – Foundations",
  shortName: "CCA-F",
  vendor: "Anthropic",
  accent: "#FB923C",
  questionCount: 60,
  timeLimitMinutes: 120,
  passingScore: 720,
  scoreScale: [0, 1000],
  scoringNote:
    "720/1000 is a scaled score. Rapids shows raw percentages with the threshold labeled: estimated — vendor uses scaled scoring; target set above the nominal threshold as a margin.",
  readinessTargetFraction: 0.8,
  domains: [
    { id: "d1", name: "Agentic Architecture & Orchestration", short: "Agentic Arch", weight: 27, color: "#C2410C" },
    { id: "d2", name: "Tool Design & MCP Integration", short: "Tools & MCP", weight: 18, color: "#0F766E" },
    { id: "d3", name: "Claude Code Configuration", short: "Claude Code", weight: 20, color: "#1E40AF" },
    { id: "d4", name: "Prompt Engineering & Structured Output", short: "Prompting", weight: 20, color: "#7C3AED" },
    { id: "d5", name: "Context Management & Reliability", short: "Context & Reliability", weight: 15, color: "#B45309" },
    { id: "proj", name: "Projects (Bonus)", short: "Projects", weight: 0, color: "#475569", bonus: true },
  ],
  registrationUrl: "https://anthropic.skilljar.com",
  officialGuideUrl:
    "https://everpath-course-content.s3-accelerate.amazonaws.com/instructor%2F8lsy243ftffjjy1cx9lm3o2bw%2Fpublic%2F1773274827%2FClaude+Certified+Architect+%E2%80%93+Foundations+Certification+Exam+Guide.pdf",
  weightsVerified: true,
  examInfo: {
    format: "60 multiple-choice questions (1 correct of 4), 120 minutes, closed-book, no AI assistance",
    passing: "720 / 1000 scaled score. No guessing penalty — answer every question.",
    scenarios: "4 of 6 scenarios randomly selected per sitting",
    proctoring: "Recording-based (not live) — take it at your convenience",
    cost: "$99 (free for first 5,000 Claude Partner Network employees)",
    scoreReport: "Delivered within 2 business days",
    experience: "6+ months building production Claude systems (Agent SDK, Claude Code, MCP, API)",
    scenarioList: [
      { name: "Customer Support Resolution Agent", gist: "Returns, billing, account issues. MCP tools: get_customer/lookup_order/process_refund/escalate_to_human. Target 80%+ first-contact resolution.", domains: "D1, D2, D5" },
      { name: "Code Generation with Claude Code", gist: "Generation, refactoring, debugging, docs. Slash commands, CLAUDE.md, plan mode vs direct execution.", domains: "D3, D5" },
      { name: "Multi-Agent Research System", gist: "Coordinator delegates to web search / document analysis / synthesis / report subagents. Reports with citations.", domains: "D1, D2, D5" },
      { name: "Developer Productivity with Claude", gist: "Codebase exploration, boilerplate, routine automation. Built-in tools + MCP servers.", domains: "D2, D3, D1" },
      { name: "Claude Code for CI/CD", gist: "Automated reviews, test generation, PR feedback. -p mode, structured output, minimize false positives.", domains: "D3, D4" },
      { name: "Structured Data Extraction", gist: "Unstructured docs → structured data. JSON Schema validation. Edge cases. High accuracy.", domains: "D4, D5" },
    ],
    inScope: [
      "Agentic loop implementation & stop_reason handling",
      "Coordinator-subagent orchestration & Task tool",
      "Subagent context management & explicit context passing",
      "Tool interface design & MCP servers/resources",
      "Error handling, structured errors & propagation",
      "Escalation decision-making & handoff protocols",
      "CLAUDE.md hierarchy & @import & .claude/rules/",
      "Slash commands, Skills (SKILL.md frontmatter)",
      "Plan mode vs direct execution",
      "Iterative refinement & the interview pattern",
      "Structured output via tool_use & JSON Schemas",
      "Few-shot prompting for consistency",
      "Message Batches API (appropriateness, custom_id)",
      "Context window optimization & lost-in-the-middle",
      "Human review workflows & confidence calibration",
      "Information provenance & conflict handling",
    ],
    outOfScope: [
      "Fine-tuning or training custom models",
      "API authentication, billing, account management",
      "Detailed language/framework implementation specifics",
      "Deploying or hosting MCP servers (infra/networking)",
      "Claude internal architecture, training, model weights",
      "Constitutional AI, RLHF, safety training",
      "Embedding models, vector database implementation",
      "Computer Use, vision/image analysis",
      "Streaming API implementation details",
      "Rate limiting, quotas, pricing calculations",
      "OAuth, API key rotation, auth protocols",
      "Cloud provider configs (AWS, GCP, Azure)",
      "Performance benchmarking or model comparison",
      "Prompt caching IMPLEMENTATION DETAILS (know it exists)",
      "Token counting algorithms or tokenization",
    ],
    exercises: [
      { title: "Build a Multi-Tool Agent with Escalation Logic", body: "Define 3–4 MCP tools with detailed descriptions that differentiate each tool. Implement an agentic loop checking stop_reason. Add structured error responses (errorCategory, isRetryable, message). Implement a programmatic hook enforcing a business rule (e.g., blocking operations over a threshold). Test with multi-concern messages.", domains: "D1, D2, D5" },
      { title: "Configure Claude Code for a Team Development Workflow", body: "Create project-level CLAUDE.md. Create .claude/rules/ files with YAML paths globs for different code areas. Create a project skill in .claude/skills/ with context:fork and allowed-tools. Configure MCP server in .mcp.json with env-var expansion and a personal server in ~/.claude.json. Test plan mode vs direct execution on tasks of varying complexity.", domains: "D3, D2" },
      { title: "Build a Structured Data Extraction Pipeline", body: "Extraction tool with required + optional + nullable fields, enum with \"other\"+detail, \"unclear\" for ambiguous. Implement validation-retry loop with Pydantic. Add few-shot examples for varied document formats. Design batch processing with custom_id failure handling. Route low-confidence extractions to human review.", domains: "D4, D5" },
      { title: "Design and Debug a Multi-Agent Research Pipeline", body: "Build coordinator with at least two subagents. Ensure coordinator's allowedTools includes \"Task\". Implement parallel execution (multiple Task calls in one response). Structured output with source attribution. Simulate timeout to test error propagation with structured context. Test conflicting sources — verify synthesis preserves both with attribution.", domains: "D1, D2, D5" },
    ],
    accessSteps: [
      "Create an Anthropic Skilljar account using your partner/company email",
      "Study using these tabs + Anthropic Academy courses (Building with Claude API is the flagship)",
      "Take the official Skilljar practice exam — unlimited retakes; aim for 900+ before the real one",
      "Complete the EAP attestation at anthropic.skilljar.com (must be logged in with partner email)",
      "Access the EAP exam — recording-based proctoring, take it on your schedule",
    ],
    courses: [
      { name: "Building with the Claude API (flagship, ~8.1hr)", url: "https://anthropic.skilljar.com/claude-with-the-anthropic-api" },
      { name: "Introduction to Model Context Protocol", url: "https://anthropic.skilljar.com/introduction-to-model-context-protocol" },
      { name: "Model Context Protocol: Advanced Topics", url: "https://anthropic.skilljar.com/model-context-protocol-advanced-topics" },
      { name: "Introduction to Subagents", url: "https://anthropic.skilljar.com/introduction-to-subagents" },
      { name: "Introduction to Agent Skills", url: "https://anthropic.skilljar.com/introduction-to-agent-skills" },
      { name: "Claude Code in Action", url: "https://anthropic.skilljar.com/claude-code-in-action" },
      { name: "Claude 101", url: "https://anthropic.skilljar.com/claude-101" },
    ],
    docLinks: [
      { name: "Official Exam Guide (PDF)", url: "https://everpath-course-content.s3-accelerate.amazonaws.com/instructor%2F8lsy243ftffjjy1cx9lm3o2bw%2Fpublic%2F1773274827%2FClaude+Certified+Architect+%E2%80%93+Foundations+Certification+Exam+Guide.pdf" },
      { name: "Messages API", url: "https://docs.claude.com/en/api/messages" },
      { name: "Tool Use", url: "https://docs.claude.com/en/docs/build-with-claude/tool-use/overview" },
      { name: "Message Batches", url: "https://docs.claude.com/en/docs/build-with-claude/batch-processing" },
      { name: "Agent SDK Overview", url: "https://platform.claude.com/docs/en/agent-sdk/overview" },
      { name: "Agent SDK Hooks", url: "https://platform.claude.com/docs/en/agent-sdk/hooks" },
      { name: "Agent SDK Subagents", url: "https://platform.claude.com/docs/en/agent-sdk/subagents" },
      { name: "Claude Code Memory/CLAUDE.md", url: "https://code.claude.com/docs/en/memory" },
      { name: "Claude Code Headless", url: "https://code.claude.com/docs/en/headless" },
      { name: "Claude Code MCP", url: "https://code.claude.com/docs/en/mcp" },
      { name: "Model Context Protocol", url: "https://modelcontextprotocol.io/" },
    ],
  },
};
