// GENERATED by scripts/migration/gen-content.mjs — 2026-08-17
// Source: jmiknuk7/exam-prep-app src/App.jsx SECTIONS (49 items; one uncited statistic deleted per Amendment 3)
// Do not hand-edit content items: regenerate, or record any manual edit in MIGRATION_NOTES.md.
import type { Section } from "../../schema";

export const sections: Section[] = [
  {
    "id": "cca-f-sec-d1-001",
    "examId": "cca-f",
    "domainId": "d1",
    "title": "Agentic Loop Lifecycle & stop_reason",
    "body": "The agentic loop: send a Messages API request with tools → receive a response → inspect stop_reason → execute any tool calls → append tool results to conversation history → iterate. The four stop_reason values are end_turn (show final response to user), tool_use (execute the tool and continue), max_tokens (truncated — increase limit), and stop_sequence (hit a configured stop string). For agentic systems, only end_turn and tool_use matter in flow control. THE ONLY RELIABLE COMPLETION SIGNAL IS stop_reason == \"end_turn\". Anti-patterns to avoid: parsing natural language for completion phrases like \"done\" or \"task complete\"; using an arbitrary iteration cap (e.g., 15 turns) as the PRIMARY stopping mechanism; checking assistant text content as a completion indicator. Iteration caps are a safety net, not termination logic.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-sec-d1-002",
    "examId": "cca-f",
    "domainId": "d1",
    "title": "Model-Driven vs Pre-Configured Decision Trees",
    "body": "Claude in an agentic loop chooses the next tool based on accumulated context and prior tool results — model-driven decision-making. This is different from hard-coded decision trees or fixed tool sequences. Model-driven is more flexible (adapts to ambiguous user requests, handles edge cases by reasoning) but less predictable. Hard-coded pipelines are predictable and cheaper but can't adapt. Common production pattern: a deterministic outer pipeline (e.g., always extract-then-enrich) combined with a model-driven inner step (Claude picks which enrichment is needed).",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-sec-d1-003",
    "examId": "cca-f",
    "domainId": "d1",
    "title": "Hub-and-Spoke: Coordinator-Subagent Architecture",
    "body": "A coordinator orchestrates multiple specialized subagents. The coordinator: decomposes tasks, dynamically selects which subagents to invoke based on query requirements (not just routing through the full pipeline every time), delegates via the Task tool, aggregates and validates results, handles errors uniformly, and routes communication. All inter-subagent communication MUST flow through the coordinator — not agent-to-agent — for observability, consistent error handling, and controlled information flow. Iterative refinement loop: the coordinator evaluates synthesis output for gaps, re-delegates to search/analysis subagents with targeted queries, re-invokes synthesis until coverage is sufficient. Over-narrow decomposition is a well-documented failure mode (e.g., decomposing \"creative industries\" as only visual arts).",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-sec-d1-004",
    "examId": "cca-f",
    "domainId": "d1",
    "title": "Task Tool & allowedTools for Spawning Subagents",
    "body": "Subagents are spawned via the Task tool. The coordinator's allowedTools MUST include \"Task\" (newer SDKs also emit \"Agent\"). Parallel subagent execution: emit multiple Task tool calls in a single coordinator RESPONSE (not across separate turns) — the SDK runs them concurrently. Explicit context passing is mandatory: subagent context must be provided directly in the prompt. Subagents do NOT automatically inherit parent context. Pattern for research: coordinator emits Task 1 (web search), Task 2 (document analysis), Task 3 (search another domain) in one response. All three run in parallel.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-sec-d1-005",
    "examId": "cca-f",
    "domainId": "d1",
    "title": "Subagent Context Isolation",
    "body": "Subagents operate with isolated context. They do NOT inherit the coordinator's conversation history, and they do NOT share memory between invocations. Any information a subagent needs must be explicitly included in its prompt. Pattern: pass complete findings from prior agents directly (e.g., web search results and document analysis outputs into the synthesis subagent's prompt). Use structured data formats to separate content from metadata (source URLs, document names, page numbers) when passing context — preserves attribution downstream. Coordinator prompts should specify research goals and quality criteria rather than step-by-step procedural instructions — this enables subagent adaptability.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-sec-d1-006",
    "examId": "cca-f",
    "domainId": "d1",
    "title": "AgentDefinition Configuration",
    "body": "AgentDefinition fields in the Claude Agent SDK: description (tells Claude when to use this subagent — this is the selection signal, write carefully), prompt (system prompt defining behavior), tools (restricted tool list — principle of least privilege), model (\"sonnet\"/\"opus\"/\"haiku\"/\"inherit\" — use cheaper models for simpler subtasks), mcpServers, skills, maxTurns. Programmatically defined agents (via the agents parameter) take precedence over filesystem-based agents with the same name. Give each subagent only the tools it needs for its role — too many tools (18 vs 4–5) degrades tool selection reliability.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-sec-d1-007",
    "examId": "cca-f",
    "domainId": "d1",
    "title": "Agent SDK Hooks — Events & Enforcement",
    "body": "Hook events: PreToolUse (before tool executes — can deny/allow/ask), PostToolUse (after tool returns — can modify output), PostToolUseFailure, UserPromptSubmit, SessionStart/SessionEnd, Stop, SubagentStart/SubagentStop, PreCompact, PermissionRequest, Notification. TypeScript adds Setup, TeammateIdle, TaskCompleted, ConfigChange, WorktreeCreate, WorktreeRemove. Hook input includes session_id, tool_name, tool_input, and for subagent calls agent_id/agent_type. PreToolUse fires BEFORE permission-mode checks — a hook that returns permissionDecision:\"deny\" blocks a tool even in bypassPermissions mode. PostToolUse cannot undo actions (tool already ran) — use it for data normalization and context injection, not for enforcement.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-sec-d1-008",
    "examId": "cca-f",
    "domainId": "d1",
    "title": "Hook Enforcement vs Prompt Guidance",
    "body": "Hooks provide DETERMINISTIC (100%) guarantees. Prompts provide PROBABILISTIC (>90%, never 100%) compliance. Rule: when failure has financial, legal, compliance, or safety consequences — use hooks, not prompts. Examples of hook patterns: (1) PostToolUse hook that normalizes heterogeneous data formats (Unix timestamps → ISO 8601, numeric status codes → labels) from different MCP tools before the agent processes them. (2) PreToolUse hook that blocks refunds above $500 and redirects to escalation. (3) Programmatic prerequisite that blocks process_refund calls until get_customer has returned a verified customer ID. Prompt instructions like \"never refund over $500\" or \"always verify customer first\" have non-zero failure rates — unacceptable when money or identity is on the line.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-sec-d1-009",
    "examId": "cca-f",
    "domainId": "d1",
    "title": "Session Management — Resume, Fork, Fresh",
    "body": "Three session patterns. --resume <session-name> continues a specific named prior session — useful for long multi-day investigations. fork_session creates independent branches from a shared analysis baseline — useful to explore divergent approaches (Redux vs Context API) without losing the common prior work. Starting FRESH with a structured summary is MORE RELIABLE than --resume when prior tool results are stale (files have changed since last session, or substantial time has passed). When resuming after code modifications, explicitly inform the agent of changes — this enables targeted re-analysis instead of forcing full re-exploration. A fresh session with a compact briefing (\"Here's what we found: [summary]. Continue by investigating X\") often beats resume with outdated tool outputs.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-sec-d1-010",
    "examId": "cca-f",
    "domainId": "d1",
    "title": "Task Decomposition Strategies",
    "body": "Two decomposition patterns. PROMPT CHAINING (fixed sequential steps) for predictable multi-aspect work: analyze each file separately, THEN run a cross-file integration pass. Use for code review, multi-pass extraction, staged pipelines. DYNAMIC ADAPTIVE DECOMPOSITION for open-ended investigation: generate subtasks based on intermediate findings. Example: \"add comprehensive tests to a legacy codebase\" → first map structure with Grep/Glob, then identify high-impact untested areas, then create a prioritized plan that adapts as dependencies are discovered. Multi-concern customer requests should be decomposed into distinct items, each investigated in parallel using shared context, then synthesized into a unified resolution. Large code reviews (10+ files): per-file local analysis passes + a separate cross-file integration pass — avoids attention dilution.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-sec-d1-011",
    "examId": "cca-f",
    "domainId": "d1",
    "title": "Structured Handoff Protocols",
    "body": "When escalating to a human, compile a structured handoff summary containing: customer ID, issue summary, root cause, order/transaction IDs, actions taken (list), relevant amounts, recommended action, escalation reason. The human operator typically does NOT have access to the full conversation transcript — the summary must be self-contained. For emotional-but-not-explicit escalation signals: acknowledge frustration → propose a concrete resolution → escalate only if customer REITERATES the desire for a human. For explicit \"get me a manager\": escalate IMMEDIATELY without first attempting to solve.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-sec-d2-001",
    "examId": "cca-f",
    "domainId": "d2",
    "title": "Tool Description Design",
    "body": "Tool descriptions are the PRIMARY mechanism LLMs use for tool selection. Minimal descriptions (\"Retrieves customer info\") cause misrouting when tools overlap. A good description includes: what the tool does and returns, input formats and example values, edge cases and constraints, explicit boundaries vs similar tools (\"Use this tool WHEN X. Use lookup_order WHEN Y\"). Write descriptions FOR THE MODEL, not the human. Rename to eliminate functional overlap: analyze_content + analyze_document → extract_web_results (web-specific) + parse_uploaded_document (file-specific). Split generic tools into purpose-specific tools with defined input/output contracts. Review system prompts for keyword-sensitive instructions that might override well-written descriptions (e.g., \"always verify the customer\" can cause get_customer overuse even when unnecessary).",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-sec-d2-002",
    "examId": "cca-f",
    "domainId": "d2",
    "title": "MCP Primitives: Tools, Resources, Prompts",
    "body": "Model Context Protocol exposes three primitive types. TOOLS are executable functions the model can call (get_customer, process_refund). RESOURCES are data the model can read for context (content catalogs, database schemas, issue/task hierarchies, documentation) — reduce exploratory tool calls by providing an immediate \"map\". PROMPTS are reusable templates invoked as /mcp__server__name. Don't force data into tools if a resource fits — resources are cheaper (no execution) and clearer. In Claude Code, reference MCP resources with @ mentions (@server:resource://id).",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-sec-d2-003",
    "examId": "cca-f",
    "domainId": "d2",
    "title": "MCP Transports: stdio, HTTP, SSE",
    "body": "Three transports. stdio runs the MCP server as a local child process over stdin/stdout — best for local development tools. Never write logs to stdout in a stdio server — corrupts JSON-RPC. HTTP (streamable with JSON-RPC) is the RECOMMENDED remote transport, supports OAuth natively. SSE (Server-Sent Events) was the original remote transport but is NOW DEPRECATED — migrate to HTTP for new remote setups. All three work interchangeably from the same Claude Code session.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-sec-d2-004",
    "examId": "cca-f",
    "domainId": "d2",
    "title": "MCP Server Configuration & Scoping",
    "body": "Project-level: .mcp.json at repo root — shared via version control, team-wide. User-level: ~/.claude.json — personal, cross-project, not shared. Use ${ENV_VAR} expansion in .mcp.json (e.g., ${GITHUB_TOKEN}) for credential management — tokens never in git. Claude Code prompts for approval before first use of project-scoped servers from .mcp.json (security). All configured MCP tools are discovered at connection time and available simultaneously. Prefer community MCP servers over custom ones for standard integrations (Jira, GitHub, Slack); reserve custom servers for team-specific workflows.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-sec-d2-005",
    "examId": "cca-f",
    "domainId": "d2",
    "title": "Structured Error Responses (isError flag)",
    "body": "MCP tool errors use isError: true with structured metadata. Include: errorCategory (\"transient\" / \"validation\" / \"business\" / \"permission\"), isRetryable (boolean), human-readable message, attempted_query, partial_results. Transient (timeout, 503) → retryable: true, local recovery in subagent. Validation (bad input) → retryable: false, fix input. Business (policy violation) → retryable: false, explain to user. Permission → retryable: false, escalate. Generic errors like \"Operation failed\" prevent intelligent recovery — the agent can't decide retry vs skip vs alternative. Distinguish ACCESS FAILURE (timeout — needs retry decision) from VALID EMPTY RESULT (\"0 matches\" — legitimate answer).",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-sec-d2-006",
    "examId": "cca-f",
    "domainId": "d2",
    "title": "Tool Distribution & Reasoning Overload",
    "body": "Giving an agent too many tools (18 vs 4–5) degrades selection reliability by increasing decision complexity. Agents with tools outside their specialization tend to misuse them (a synthesis agent with web_search will run ad-hoc queries that should go through the search agent). Scoped tool access: give each agent ONLY the tools for its role, plus limited cross-role tools for high-frequency needs (e.g., a verify_fact tool for the synthesis agent, with complex verifications still going through the coordinator). Replace generic tools with constrained alternatives — fetch_url → load_document (validates URL type), blocking undesired search behavior at the interface.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-sec-d2-007",
    "examId": "cca-f",
    "domainId": "d2",
    "title": "tool_choice Parameter",
    "body": "Three configurations. \"auto\" — model decides whether to call a tool or return text. Default for most cases. \"any\" — model MUST call SOME tool but can choose which. Use when you want guaranteed structured output and multiple extraction schemas exist (unknown document type). {\"type\": \"tool\", \"name\": \"extract_metadata\"} — model MUST call a specific named tool. Use to force execution order (e.g., always run extract_metadata before enrichment in subsequent turns).",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-sec-d2-008",
    "examId": "cca-f",
    "domainId": "d2",
    "title": "Built-in Tools (Read/Write/Edit/Bash/Grep/Glob)",
    "body": "Grep — search within file contents (function names, error messages, imports). Glob — match file paths by pattern (**/*.test.tsx, src/**/*.ts). Read — load full file content. Write — create new file. Edit — precise in-place edits via unique text match. Bash — run shell commands. Pattern for incremental investigation: Glob to find files → Grep to narrow → Read to understand → Edit to change. Do NOT read all files upfront. When Edit fails due to non-unique text match, fall back to Read + Write. Trace function usage across wrappers: identify all exported names, then Grep each name across the codebase.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-sec-d3-001",
    "examId": "cca-f",
    "domainId": "d3",
    "title": "CLAUDE.md Configuration Hierarchy",
    "body": "Three levels. USER-LEVEL: ~/.claude/CLAUDE.md applies only to that user, NOT shared via version control — for personal preferences. PROJECT-LEVEL: .claude/CLAUDE.md (preferred) or root CLAUDE.md — version-controlled, applies to all team members, for coding standards, testing conventions, architectural decisions. DIRECTORY-LEVEL: CLAUDE.md in subdirectories — applies when working with files in that directory, for part-of-codebase conventions. Common exam trap: a new team member doesn't receive project context because conventions were stored in ~/.claude/CLAUDE.md instead of .claude/CLAUDE.md committed to git. Use /memory command to verify which files are loaded and diagnose inconsistent cross-session behavior.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-sec-d3-002",
    "examId": "cca-f",
    "domainId": "d3",
    "title": "@import Syntax for Modular CLAUDE.md",
    "body": "CLAUDE.md supports @path imports for modular composition: @./standards/coding-style.md pulls in another file. Rules: @ immediately before the path (no space); relative or absolute paths accepted; relative paths resolve relative to the IMPORTING file; maximum nesting depth is 5. Use @imports in a monorepo: each package's CLAUDE.md imports only the shared standards that apply (one imports api-conventions.md, another imports react-patterns.md). Keeps CLAUDE.md files focused without duplication.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-sec-d3-003",
    "examId": "cca-f",
    "domainId": "d3",
    "title": ".claude/rules/ with YAML paths Frontmatter",
    "body": "Alternative to monolithic CLAUDE.md: .claude/rules/ directory of topic-specific rule files. Each file has YAML frontmatter with glob patterns — paths: [\"**/*.test.tsx\"] — and loads ONLY when editing matching files. Saves tokens, reduces irrelevant context. Perfect for conventions that SPAN MULTIPLE DIRECTORIES (test files scattered throughout, all Terraform files, all migration scripts). Choose path-specific rules over directory-level CLAUDE.md when files live in many locations; choose directory CLAUDE.md when conventions cluster in one spot and are irrelevant elsewhere.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-sec-d3-004",
    "examId": "cca-f",
    "domainId": "d3",
    "title": "Custom Slash Commands",
    "body": "Slash commands are reusable prompt templates invoked with /name. PROJECT commands: .claude/commands/ — committed to VCS, shared team-wide (running /review triggers the markdown content of .claude/commands/review.md as a prompt). PERSONAL commands: ~/.claude/commands/ — local only. $ARGUMENTS placeholder passes arguments. Use slash commands for workflows developers invoke explicitly.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-sec-d3-005",
    "examId": "cca-f",
    "domainId": "d3",
    "title": "Agent Skills with SKILL.md Frontmatter",
    "body": "Skills are advanced auto-discovered capabilities. Each lives in .claude/skills/name/SKILL.md with YAML frontmatter. Key frontmatter: context: fork (runs skill in isolated sub-agent — verbose output does NOT pollute main session), allowed-tools (tool allowlist — restricts what the skill can use for security, e.g., only Read operations to prevent destructive actions), argument-hint (prompts developer for required parameters when invoked without args). Personal skill variants: ~/.claude/skills/ with different names so you don't affect teammates. SKILL vs SLASH COMMAND: skills are AUTO-DISCOVERED by Claude when relevant (Claude picks based on SKILL.md); slash commands are EXPLICITLY invoked by the user.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-sec-d3-006",
    "examId": "cca-f",
    "domainId": "d3",
    "title": "Plan Mode vs Direct Execution",
    "body": "PLAN MODE: Claude explores the codebase (Read, Grep, Glob) and produces an implementation plan for you to approve — no side effects, safe exploration. Use for: large-scale changes affecting many files, multiple viable implementation approaches, architectural decisions, unfamiliar codebases, library migrations touching 45+ files, microservice restructuring. DIRECT EXECUTION: make changes immediately. Use for: single-file, well-scoped changes (adding one validation check, a fix with a clear stack trace). COMBINED: plan mode for investigation → user approves → direct execution for implementation. EXPLORE subagent isolates verbose discovery output from the main context, returning condensed summaries. Use it for multi-phase tasks to prevent context-window exhaustion.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-sec-d3-007",
    "examId": "cca-f",
    "domainId": "d3",
    "title": "Iterative Refinement Techniques",
    "body": "Concrete input/output examples are the MOST effective way to communicate expected transformations when prose descriptions produce inconsistent results. Provide 2–3 I/O examples. TEST-DRIVEN ITERATION: write a test suite covering expected behavior, edge cases, and performance requirements FIRST, then iterate by sharing test failures. INTERVIEW PATTERN: have Claude ask questions to surface design considerations you may not have anticipated (cache invalidation strategies, failure modes, data volume expectations) — useful in unfamiliar domains (fintech, healthcare, legal). Multiple INTERACTING issues → fix in one detailed message (fixes affect each other). INDEPENDENT issues → fix sequentially.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-sec-d3-008",
    "examId": "cca-f",
    "domainId": "d3",
    "title": "Claude Code Headless Mode for CI/CD",
    "body": "The -p (or --print) flag is the ONLY correct way to run Claude Code in a CI/CD pipeline. Non-interactive: processes prompt → outputs to stdout → exits. Three output formats. text (default, raw to stdout). json (structured: result, model, usage, cost_usd, duration_ms, num_turns, session_id, stop_reason). stream-json (NDJSON for real-time progress). --json-schema enforces a schema on the result content. --allowedTools \"Read,Grep,Glob\" restricts what Claude can use. --max-turns caps agent iterations. --bare skips OAuth and keychain reads (recommended for scripted/SDK calls; will become the default for -p). Pair with a Unix timeout for safety.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ],
    "unverifiedClaims": [
      "\"--bare skips OAuth and keychain reads ... will become the default for -p\" — product behavior claim, checkable against Claude Code docs; not yet verified."
    ]
  },
  {
    "id": "cca-f-sec-d3-009",
    "examId": "cca-f",
    "domainId": "d3",
    "title": "CI/CD Best Practices & Session Isolation",
    "body": "Session context isolation: the same Claude session that generated code is LESS EFFECTIVE at reviewing its own changes — it retains reasoning context and is biased toward its own decisions. Use an INDEPENDENT instance for review. Include prior review findings in the prompt when re-running after new commits, with instruction to report only NEW or still-unresolved issues — prevents duplicate comments on every push. Include existing test files in context when generating new tests so suggestions avoid duplication. Document testing standards, available fixtures, and review criteria in CLAUDE.md — dramatically improves test generation quality and reduces low-value output.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-sec-d3-010",
    "examId": "cca-f",
    "domainId": "d3",
    "title": "/compact and /memory Commands",
    "body": "/compact summarizes prior history to free the context window — used in long sessions when tool outputs have accumulated. RISK: exact numerics, dates, and specific values can be lost to vague summaries (\"about $89\" instead of \"$89.99\"). Extract critical facts to a persistent block BEFORE compacting. /memory opens CLAUDE.md for editing mid-session and verifies which memory files are currently loaded — useful for diagnosing why conventions aren't being applied. Prefer /compact over /clear when you want to keep state; compaction preserves prefix cache for the next turn.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-sec-d4-001",
    "examId": "cca-f",
    "domainId": "d4",
    "title": "Explicit Criteria Over Vague Instructions",
    "body": "Vague instructions fail: \"be conservative\", \"only flag high-confidence issues\", \"check that comments are accurate\". The model cannot calibrate vague caution. EXPLICIT CRITERIA work: \"Flag a comment ONLY if (1) it describes behavior that contradicts the code, (2) it references a nonexistent function, or (3) it's a TODO/FIXME already fixed in code. Do NOT flag stylistically outdated comments or minor wording issues.\" Define WHAT to flag (and NOT flag), not HOW CAREFUL to be. High false-positive rates in some categories undermine developer trust across ALL categories — temporarily disable the worst-offender categories while improving their prompts. Define severity levels with CONCRETE CODE EXAMPLES per level (CRITICAL: runtime failure during payment processing; HIGH: SQL injection vector; MEDIUM: off-by-one error; LOW: duplication).",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-sec-d4-002",
    "examId": "cca-f",
    "domainId": "d4",
    "title": "Few-Shot Prompting: The Most Effective Technique",
    "body": "Few-shot examples are the MOST EFFECTIVE technique for achieving consistent, actionable output when detailed instructions alone produce inconsistency. 2–4 targeted examples is the sweet spot — diminishing returns past 4, plus token cost. Types: (1) examples for ambiguous scenarios WITH RATIONALE showing why one action was chosen over alternatives; (2) output format examples (location, issue, severity, suggested fix); (3) acceptable-vs-problematic pairs to reduce false positives while preserving generalization; (4) extraction from varied document structures (inline citations vs bibliographies, narrative vs table); (5) informal measurements (\"two handfuls\" → \"~100g\"). Few-shot enables the model to GENERALIZE to novel patterns — not just match pre-specified cases. Place examples where they most affect judgment (system prompt for persistent behavior, user message for one-off).",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-sec-d4-003",
    "examId": "cca-f",
    "domainId": "d4",
    "title": "tool_use for Guaranteed Structured Output",
    "body": "tool_use with JSON Schemas is the MOST RELIABLE approach for guaranteed schema-compliant output — eliminates JSON syntax errors (no missing braces, wrong types). Define extraction tools with input_schema (the tool's input IS your output schema). Pattern: define the tool, force it with tool_choice, parse the tool_use block from the response. tool_use does NOT prevent SEMANTIC errors: line items not summing to total, values in wrong fields, fabricated content. Use Pydantic validators or custom validation logic for semantic checks.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-sec-d4-004",
    "examId": "cca-f",
    "domainId": "d4",
    "title": "Schema Design: Required, Nullable, Enum Patterns",
    "body": "REQUIRED vs OPTIONAL: mark a field required only when info is ALWAYS present. Required on possibly-missing data pushes the model to fabricate values. NULLABLE: use \"type\": [\"string\", \"null\"] for fields that may be absent — the model returns null honestly instead of hallucinating. ENUM ESCAPE HATCHES: include \"other\" (plus a detail string field) for values outside predefined categories, and \"unclear\" for cases where the model genuinely can't decide. Honest \"unclear\" beats a confident wrong category. FORMAT NORMALIZATION RULES go in the PROMPT alongside the schema: \"Dates: ISO 8601 YYYY-MM-DD; 'yesterday' → compute absolute date. Currency: numeric + currency code; 'five bucks' → {amount:5, currency:'USD'}. Percentages: decimal; 'half' → 0.5.\"",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-sec-d4-005",
    "examId": "cca-f",
    "domainId": "d4",
    "title": "Validation-Retry Loops with Error Feedback",
    "body": "When extracted data fails validation: send a follow-up request including (1) the ORIGINAL document, (2) the PREVIOUS (incorrect) extraction, (3) the SPECIFIC validation error (\"Field total=150 but sum(line_items)=145. Re-check\"). Cap retries at 2–3. RETRIES HELP for: format mismatches (date in wrong format), structural errors (value in wrong field), arithmetic inconsistencies the model can self-check. RETRIES DO NOT HELP when the required info is simply ABSENT from the source document (vs external). Recognize this class — return null or escalate. Add a detected_pattern field in findings to enable analysis of which patterns trigger false positives when devs dismiss.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-sec-d4-006",
    "examId": "cca-f",
    "domainId": "d4",
    "title": "Self-Correction Patterns",
    "body": "Extract both calculated and stated values to detect internal contradictions. Example: { stated_total: \"$150.00\", calculated_total: \"$145.00\", conflict_detected: true, line_items: [...] }. Downstream code handles the discrepancy explicitly. For multi-source synthesis with potentially conflicting data: preserve BOTH values with attribution, annotate conflict_detected, include methodology and date fields. Do NOT arbitrarily pick — let the coordinator reconcile.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-sec-d4-007",
    "examId": "cca-f",
    "domainId": "d4",
    "title": "Message Batches API",
    "body": "Message Batches API: 50% cost savings vs synchronous API, up to 24-hour processing window, NO guaranteed latency SLA. Multi-turn tool calling is NOT SUPPORTED — batches are fire-and-forget, one request → one response. custom_id field correlates request/response pairs (required for any real use). USE BATCHES FOR: overnight tech-debt reports, weekly security audits, nightly test generation, bulk document extraction (10K+ docs), non-blocking workloads. DO NOT USE FOR: pre-merge PR checks (blocking), interactive reviews, live customer interactions, iterative tool-calling workflows. SLA planning: for a 30-hour guarantee with 24-hour processing, submit by the 6-hour mark. FAILURE HANDLING: identify failures by custom_id, re-submit only failed items with modifications (e.g., chunking oversized documents). Refine prompts on a sample before running bulk batches.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-sec-d4-008",
    "examId": "cca-f",
    "domainId": "d4",
    "title": "Multi-Pass Review Architecture",
    "body": "Self-review limitation: a model retains its reasoning context from generation, making it LESS LIKELY to question its own decisions in the same session — confirmation bias. Fix: run review in a SECOND INDEPENDENT Claude instance without the generator's history. This \"fresh eyes\" approach mirrors human peer review. For 10+ file PRs: Pass 1 — per-file local analysis (consistent depth per file). Pass 2 — cross-file integration pass (dataflow, type consistency, circular dependencies). Why single-pass over 14 files fails: ATTENTION DILUTION — detailed analysis on some files, shallow on others, contradictory patterns flagged-here-but-approved-there. Larger context windows do NOT fix attention quality. Verification passes where the model self-reports confidence alongside each finding enables calibrated routing.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-sec-d4-009",
    "examId": "cca-f",
    "domainId": "d4",
    "title": "Prompt Caching (Concept Only — Out of Scope)",
    "body": "The exam guide explicitly lists \"prompt caching implementation details (beyond knowing it exists)\" as OUT OF SCOPE. Know the concept: prompt caching lets you mark portions of the prompt (via cache_control) so reused prefixes cost less on subsequent requests — used to reduce costs for long system prompts or large contexts reused across many calls. You do not need to memorize TTL specifics, minimum token thresholds, cache_creation_input_tokens response fields, or breakpoint placement rules. If a question frames caching as a cost mechanism and asks about concept-level decisions, use common sense; the exam will not require implementation math.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-sec-d5-001",
    "examId": "cca-f",
    "domainId": "d5",
    "title": "Long-Context Management",
    "body": "Three core risks. (1) PROGRESSIVE SUMMARIZATION degrades precise values: numeric amounts, percentages, dates, customer-stated expectations become vague (\"about\", \"roughly\", \"a few\"). (2) LOST-IN-THE-MIDDLE: models reliably process the start and end of long inputs but may MISS findings from middle sections. (3) TOOL RESULT ACCUMULATION: a lookup_order returning 40+ fields when only 5 are relevant wastes context tokens disproportionately. Mitigations: extract transactional facts (order IDs, amounts, dates, statuses) into a persistent \"case facts\" BLOCK included in every prompt, OUTSIDE the summarized history. Trim verbose tool outputs to only relevant fields (PostToolUse hook). Place key findings SUMMARIES at the BEGINNING of aggregated inputs with explicit section headers to mitigate position effects. Always pass complete conversation history in subsequent API requests.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-sec-d5-002",
    "examId": "cca-f",
    "domainId": "d5",
    "title": "Escalation Triggers — Appropriate vs Unreliable",
    "body": "APPROPRIATE escalation triggers: (1) Customer EXPLICITLY requests a human (\"get me a manager\") → escalate IMMEDIATELY, do not attempt investigation first. (2) Policy is AMBIGUOUS or SILENT on the specific request (competitor price-matching when policy only addresses own-site adjustments) → escalate. (3) Agent cannot make meaningful progress after reasonable attempts. (4) Financial operation above threshold (ENFORCE via hook, not prompt). (5) Multiple customer matches → ask for additional identifiers, DO NOT guess by heuristic. UNRELIABLE triggers that FAIL: sentiment analysis (frustration ≠ case complexity), self-reported confidence scores (the model is confidently wrong on hard cases — poor calibration), auto-classifiers (over-engineering; requires labeled data you may not have). For frustration without explicit escalation request: acknowledge → propose concrete resolution → escalate only if customer REITERATES.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-sec-d5-003",
    "examId": "cca-f",
    "domainId": "d5",
    "title": "Error Propagation in Multi-Agent Systems",
    "body": "Return structured error context to the coordinator — not generic failure statuses — so it can make intelligent recovery decisions. Include: failure_type, what was attempted (attempted_query), partial results (if any), potential alternative approaches, coverage_impact. ANTI-PATTERNS: (1) Generic \"search unavailable\" hides context. (2) Silent suppression — returning empty results as success — prevents any recovery and risks incomplete outputs. (3) Terminating the entire workflow on a single subagent failure. (4) Infinite retries inside a subagent. PATTERN: local recovery inside subagents for TRANSIENT failures; propagate only errors the subagent CANNOT resolve, with partial results and what was attempted. Distinguish ACCESS FAILURES (timeouts — need retry decisions) from VALID EMPTY RESULTS (successful query with no matches). Structure synthesis output with COVERAGE ANNOTATIONS: \"FULL COVERAGE\" vs \"PARTIAL COVERAGE — search timed out\" so readers know what's well-supported vs. gap.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-sec-d5-004",
    "examId": "cca-f",
    "domainId": "d5",
    "title": "Large Codebase Exploration",
    "body": "Context degradation in extended sessions: the model starts giving inconsistent answers and referencing \"typical patterns\" rather than the specific classes it discovered earlier. Mitigations: (1) SCRATCHPAD FILES (investigation-scratchpad.md, plan.md) record key findings — the agent reads them for subsequent questions to counteract degradation. (2) SUBAGENT DELEGATION isolates verbose exploration output — spawn subagents for specific questions (\"find all test files\", \"trace refund flow dependencies\") while the main agent preserves high-level coordination. Subagent reads 50 files and returns only a summary; main coordinator never sees raw contents. (3) Summarize key findings from one exploration phase BEFORE spawning subagents for the next phase; inject summaries into initial context. (4) STRUCTURED STATE PERSISTENCE for crash recovery: each agent exports state to a manifest file (agent-state/web-search.json with status, queries_executed, key_findings, coverage, gaps). Coordinator loads the manifest on resume. (5) /compact reduces context usage mid-exploration.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-sec-d5-005",
    "examId": "cca-f",
    "domainId": "d5",
    "title": "Human Review & Confidence Calibration",
    "body": "Aggregate metrics hide failure modes. 97% overall accuracy can mask 40% error rates on specific document types or fields. STRATIFIED RANDOM SAMPLING: audit high-confidence extractions per-document-type AND per-field to measure ongoing error rates and detect novel patterns. Validate accuracy by document type AND field segment BEFORE reducing human review. Have models output FIELD-LEVEL confidence scores. Calibrate review thresholds EMPIRICALLY using labeled validation sets — not by guessing. Route low-confidence or ambiguous-source extractions to human review. Recalibrate when prompt or model changes.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-sec-d5-006",
    "examId": "cca-f",
    "domainId": "d5",
    "title": "Information Provenance & Multi-Source Synthesis",
    "body": "Attribution is often LOST during summarization when findings are compressed without preserving claim-source mappings. Require subagents to output STRUCTURED claim-source mappings: source URL, document name, relevant excerpt/quote, publication or data collection date. Downstream synthesis MUST preserve these through aggregation. For CONFLICTING statistics from credible sources: annotate both values with source attribution and methodology — NEVER arbitrarily select one. Include publication DATES so temporal differences aren't misread as contradictions (\"Source A 10% in 2023, Source B 15% in 2024\" = trend, not conflict). Structure reports with explicit sections distinguishing well-established findings from contested ones, preserving original source characterizations and methodological context. Render content APPROPRIATELY: financial data as tables, news as prose, technical findings as structured lists, time series chronologically — don't force everything into a uniform format.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-sec-proj-001",
    "examId": "cca-f",
    "domainId": "proj",
    "title": "What Projects Are",
    "body": "Self-contained workspaces with their own memory, chat histories, knowledge bases, and custom instructions. Use for ongoing work with reused reference materials, consistent requirements across chats, or team collaboration. Not for one-off questions. Each project chat automatically accesses its knowledge base and follows its instructions.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-sec-proj-002",
    "examId": "cca-f",
    "domainId": "proj",
    "title": "Project Instructions",
    "body": "Instructions guide Claude across every chat in a project. Good ones include: context (what the work is), process (steps), tone/style, specific requirements. Instructions can automate workflows (\"when I upload a transcript, summarize using this template\"). Work alongside user preferences and custom styles.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-sec-proj-003",
    "examId": "cca-f",
    "domainId": "proj",
    "title": "Knowledge Base & RAG",
    "body": "Upload PDFs, DOCX, CSVs, TXT, HTML. Descriptive filenames help retrieval. When knowledge approaches context limits, Projects automatically switch to RAG mode: retrieves most-relevant chunks rather than loading everything. Capacity expands up to 10x. Visual indicator shows when RAG is active.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-sec-proj-004",
    "examId": "cca-f",
    "domainId": "proj",
    "title": "Permission Levels",
    "body": "Can view (read + chat, no edits). Can edit (modify instructions, knowledge, members). Owner (controls sharing and visibility). Share by email or make visible to the whole organization.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  },
  {
    "id": "cca-f-sec-proj-005",
    "examId": "cca-f",
    "domainId": "proj",
    "title": "Best Practices",
    "body": "Start focused, expand later. Keep knowledge current. Write specific, example-driven instructions. Name files descriptively. Reference docs by name in chats (\"based on our Q3 report...\") to focus retrieval.",
    "sourceIds": [
      "ccaf-exam-guide",
      "ccaf-src-exam-prep-app"
    ]
  }
];
